/* eslint-disable */
// AUTO-GENERATED by scripts/gen-migration-bundles.ts — do not edit by hand.
// Run `bun scripts/gen-migration-bundles.ts` after adding a migration to
// regenerate. The CI hook will fail if this file is out of sync.

import m0 from "../../drizzle/pg/20260503000000_pg_baseline/migration.sql" with { type: "text" };
import m1 from "../../drizzle/pg/20260504034557_quick_northstar/migration.sql" with { type: "text" };
import m2 from "../../drizzle/pg/20260504041009_bouncy_network/migration.sql" with { type: "text" };
import m3 from "../../drizzle/pg/20260504185448_aspiring_the_santerians/migration.sql" with { type: "text" };
import m4 from "../../drizzle/pg/20260504190033_new_maria_hill/migration.sql" with { type: "text" };
import m5 from "../../drizzle/pg/20260504190300_neat_shard/migration.sql" with { type: "text" };
import m6 from "../../drizzle/pg/20260504194132_sloppy_squadron_supreme/migration.sql" with { type: "text" };
import m7 from "../../drizzle/pg/20260504194244_solid_storm/migration.sql" with { type: "text" };
import m8 from "../../drizzle/pg/20260504194512_cute_peter_parker/migration.sql" with { type: "text" };
import m9 from "../../drizzle/pg/20260504203509_nice_bill_hollister/migration.sql" with { type: "text" };
import m10 from "../../drizzle/pg/20260504215116_certain_richard_fisk/migration.sql" with { type: "text" };
import m11 from "../../drizzle/pg/20260509000000_pg_chain_columns/migration.sql" with { type: "text" };
import m12 from "../../drizzle/pg/20260510120000_per_workspace_collections/migration.sql" with { type: "text" };
import m13 from "../../drizzle/pg/20260510130000_flow_layout/migration.sql" with { type: "text" };
import m14 from "../../drizzle/pg/20260510140000_scheduled_tasks/migration.sql" with { type: "text" };
import m15 from "../../drizzle/pg/20260510150000_folders_tenant_id/migration.sql" with { type: "text" };
import m16 from "../../drizzle/pg/20260510160000_roles_apikeys_tenant_id/migration.sql" with { type: "text" };
import m17 from "../../drizzle/pg/20260510170000_seed_tenant_roles/migration.sql" with { type: "text" };
import m18 from "../../drizzle/pg/20260511000000_api_key_role_scope/migration.sql" with { type: "text" };
import m19 from "../../drizzle/pg/20260511120000_app_user_pool/migration.sql" with { type: "text" };
import m20 from "../../drizzle/pg/20260511120000_email_templates_pg/migration.sql" with { type: "text" };
import m21 from "../../drizzle/pg/20260511130000_app_user_roles/migration.sql" with { type: "text" };
import m22 from "../../drizzle/pg/20260512000000_email_config/migration.sql" with { type: "text" };
import m23 from "../../drizzle/pg/20260513120000_collections_vectorize/migration.sql" with { type: "text" };
import m24 from "../../drizzle/pg/20260513140000_activity_response/migration.sql" with { type: "text" };
import m25 from "../../drizzle/pg/20260513200000_workspace_config/migration.sql" with { type: "text" };
import m26 from "../../drizzle/pg/20260516000000_saml_sso/migration.sql" with { type: "text" };
import m27 from "../../drizzle/pg/20260517000000_ldap_sso/migration.sql" with { type: "text" };
import m28 from "../../drizzle/pg/20260517100000_collection_default_sort/migration.sql" with { type: "text" };
import m29 from "../../drizzle/pg/20260517110000_collection_adopt/migration.sql" with { type: "text" };
import m30 from "../../drizzle/pg/20260517120000_collection_system_aliases/migration.sql" with { type: "text" };
import m31 from "../../drizzle/pg/20260517130000_collection_soft_delete/migration.sql" with { type: "text" };
import m32 from "../../drizzle/pg/20260517130000_drop_site_name_setting/migration.sql" with { type: "text" };
import m33 from "../../drizzle/pg/20260520000000_shared_links/migration.sql" with { type: "text" };
import m34 from "../../drizzle/pg/20260520190000_workspace_theme_colors/migration.sql" with { type: "text" };
import m35 from "../../drizzle/pg/20260522120000_user_locale_timezone/migration.sql" with { type: "text" };
import m36 from "../../drizzle/pg/20260525010000_api_keys_mcp_metadata/migration.sql" with { type: "text" };
import m37 from "../../drizzle/pg/20260601210000_integrations/migration.sql" with { type: "text" };

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { name: "20260503000000_pg_baseline", sql: m0 },
  { name: "20260504034557_quick_northstar", sql: m1 },
  { name: "20260504041009_bouncy_network", sql: m2 },
  { name: "20260504185448_aspiring_the_santerians", sql: m3 },
  { name: "20260504190033_new_maria_hill", sql: m4 },
  { name: "20260504190300_neat_shard", sql: m5 },
  { name: "20260504194132_sloppy_squadron_supreme", sql: m6 },
  { name: "20260504194244_solid_storm", sql: m7 },
  { name: "20260504194512_cute_peter_parker", sql: m8 },
  { name: "20260504203509_nice_bill_hollister", sql: m9 },
  { name: "20260504215116_certain_richard_fisk", sql: m10 },
  { name: "20260509000000_pg_chain_columns", sql: m11 },
  { name: "20260510120000_per_workspace_collections", sql: m12 },
  { name: "20260510130000_flow_layout", sql: m13 },
  { name: "20260510140000_scheduled_tasks", sql: m14 },
  { name: "20260510150000_folders_tenant_id", sql: m15 },
  { name: "20260510160000_roles_apikeys_tenant_id", sql: m16 },
  { name: "20260510170000_seed_tenant_roles", sql: m17 },
  { name: "20260511000000_api_key_role_scope", sql: m18 },
  { name: "20260511120000_app_user_pool", sql: m19 },
  { name: "20260511120000_email_templates_pg", sql: m20 },
  { name: "20260511130000_app_user_roles", sql: m21 },
  { name: "20260512000000_email_config", sql: m22 },
  { name: "20260513120000_collections_vectorize", sql: m23 },
  { name: "20260513140000_activity_response", sql: m24 },
  { name: "20260513200000_workspace_config", sql: m25 },
  { name: "20260516000000_saml_sso", sql: m26 },
  { name: "20260517000000_ldap_sso", sql: m27 },
  { name: "20260517100000_collection_default_sort", sql: m28 },
  { name: "20260517110000_collection_adopt", sql: m29 },
  { name: "20260517120000_collection_system_aliases", sql: m30 },
  { name: "20260517130000_collection_soft_delete", sql: m31 },
  { name: "20260517130000_drop_site_name_setting", sql: m32 },
  { name: "20260520000000_shared_links", sql: m33 },
  { name: "20260520190000_workspace_theme_colors", sql: m34 },
  { name: "20260522120000_user_locale_timezone", sql: m35 },
  { name: "20260525010000_api_keys_mcp_metadata", sql: m36 },
  { name: "20260601210000_integrations", sql: m37 },
];
