/* eslint-disable */
// AUTO-GENERATED by scripts/gen-migration-bundles.ts — do not edit by hand.
// Run `bun scripts/gen-migration-bundles.ts` after adding a migration to
// regenerate. The CI hook will fail if this file is out of sync.

import m0 from "../../drizzle/pg/20260503000000_pg_baseline/migration.sql" with { type: "text" };
import m1 from "../../drizzle/pg/20260504034557_quick_northstar/migration.sql" with { type: "text" };
import m2 from "../../drizzle/pg/20260504041009_bouncy_network/migration.sql" with { type: "text" };
import m3 from "../../drizzle/pg/20260504185448_aspiring_the_santerians/migration.sql" with { type: "text" };
import m4 from "../../drizzle/pg/20260504190033_new_maria_hill/migration.sql" with { type: "text" };
import m5 from "../../drizzle/pg/20260504190300_neat_shard/migration.sql" with { type: "text" };
import m6 from "../../drizzle/pg/20260504194132_sloppy_squadron_supreme/migration.sql" with { type: "text" };
import m7 from "../../drizzle/pg/20260504194244_solid_storm/migration.sql" with { type: "text" };
import m8 from "../../drizzle/pg/20260504194512_cute_peter_parker/migration.sql" with { type: "text" };
import m9 from "../../drizzle/pg/20260504203509_nice_bill_hollister/migration.sql" with { type: "text" };
import m10 from "../../drizzle/pg/20260504215116_certain_richard_fisk/migration.sql" with { type: "text" };
import m11 from "../../drizzle/pg/20260509000000_pg_chain_columns/migration.sql" with { type: "text" };
import m12 from "../../drizzle/pg/20260510120000_per_workspace_collections/migration.sql" with { type: "text" };
import m13 from "../../drizzle/pg/20260510130000_flow_layout/migration.sql" with { type: "text" };
import m14 from "../../drizzle/pg/20260510140000_scheduled_tasks/migration.sql" with { type: "text" };
import m15 from "../../drizzle/pg/20260510150000_folders_tenant_id/migration.sql" with { type: "text" };
import m16 from "../../drizzle/pg/20260510160000_roles_apikeys_tenant_id/migration.sql" with { type: "text" };
import m17 from "../../drizzle/pg/20260510170000_seed_tenant_roles/migration.sql" with { type: "text" };
import m18 from "../../drizzle/pg/20260511000000_api_key_role_scope/migration.sql" with { type: "text" };
import m19 from "../../drizzle/pg/20260511120000_app_user_pool/migration.sql" with { type: "text" };
import m20 from "../../drizzle/pg/20260511120000_email_templates_pg/migration.sql" with { type: "text" };
import m21 from "../../drizzle/pg/20260511130000_app_user_roles/migration.sql" with { type: "text" };
import m22 from "../../drizzle/pg/20260512000000_email_config/migration.sql" with { type: "text" };
import m23 from "../../drizzle/pg/20260513120000_collections_vectorize/migration.sql" with { type: "text" };
import m24 from "../../drizzle/pg/20260513140000_activity_response/migration.sql" with { type: "text" };
import m25 from "../../drizzle/pg/20260513200000_workspace_config/migration.sql" with { type: "text" };
import m26 from "../../drizzle/pg/20260516000000_saml_sso/migration.sql" with { type: "text" };
import m27 from "../../drizzle/pg/20260517000000_ldap_sso/migration.sql" with { type: "text" };
import m28 from "../../drizzle/pg/20260517100000_collection_default_sort/migration.sql" with { type: "text" };
import m29 from "../../drizzle/pg/20260517110000_collection_adopt/migration.sql" with { type: "text" };
import m30 from "../../drizzle/pg/20260517120000_collection_system_aliases/migration.sql" with { type: "text" };
import m31 from "../../drizzle/pg/20260517130000_collection_soft_delete/migration.sql" with { type: "text" };
import m32 from "../../drizzle/pg/20260517130000_drop_site_name_setting/migration.sql" with { type: "text" };
import m33 from "../../drizzle/pg/20260520000000_shared_links/migration.sql" with { type: "text" };
import m34 from "../../drizzle/pg/20260520190000_workspace_theme_colors/migration.sql" with { type: "text" };
import m35 from "../../drizzle/pg/20260522120000_user_locale_timezone/migration.sql" with { type: "text" };
import m36 from "../../drizzle/pg/20260525010000_api_keys_mcp_metadata/migration.sql" with { type: "text" };
import m37 from "../../drizzle/pg/20260601210000_integrations/migration.sql" with { type: "text" };
import m38 from "../../drizzle/pg/20260603120000_collections_soft_delete_singleton/migration.sql" with { type: "text" };
import m39 from "../../drizzle/pg/20260604120000_passkey_aaguid/migration.sql" with { type: "text" };
import m40 from "../../drizzle/pg/20260609120000_collections_audit_reads/migration.sql" with { type: "text" };
import m41 from "../../drizzle/pg/20260613120000_platform_sso/migration.sql" with { type: "text" };
import m42 from "../../drizzle/pg/20260618120000_two_factor/migration.sql" with { type: "text" };
import m43 from "../../drizzle/pg/20260620120000_push_messaging/migration.sql" with { type: "text" };
import m44 from "../../drizzle/pg/20260620130000_sms_messaging/migration.sql" with { type: "text" };
import m45 from "../../drizzle/pg/20260620150000_job_queue/migration.sql" with { type: "text" };
import m46 from "../../drizzle/pg/20260620160000_uploads/migration.sql" with { type: "text" };
import m47 from "../../drizzle/pg/20260620170000_feature_flags/migration.sql" with { type: "text" };
import m48 from "../../drizzle/pg/20260620180000_collections_fts/migration.sql" with { type: "text" };
import m49 from "../../drizzle/pg/20260620190000_managed_webhooks/migration.sql" with { type: "text" };
import m50 from "../../drizzle/pg/20260621000000_ai_config/migration.sql" with { type: "text" };
import m51 from "../../drizzle/pg/20260627000000_ai_agents/migration.sql" with { type: "text" };
import m52 from "../../drizzle/pg/20260628000000_request_spans/migration.sql" with { type: "text" };
import m53 from "../../drizzle/pg/20260628100000_dashboards/migration.sql" with { type: "text" };
import m54 from "../../drizzle/pg/20260630120000_schema_versions/migration.sql" with { type: "text" };
import m55 from "../../drizzle/pg/20260701120000_sessions_created_idx/migration.sql" with { type: "text" };
import m56 from "../../drizzle/pg/20260702120000_activity_tenant_created_idx/migration.sql" with { type: "text" };
import m57 from "../../drizzle/pg/20260702130000_embeddings_per_model/migration.sql" with { type: "text" };
import m58 from "../../drizzle/pg/20260702150000_collection_pk_type/migration.sql" with { type: "text" };
import m59 from "../../drizzle/pg/20260703090000_external_migration/migration.sql" with { type: "text" };
import m60 from "../../drizzle/pg/20260704090000_collection_grouping/migration.sql" with { type: "text" };

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { name: "20260503000000_pg_baseline", sql: m0 },
  { name: "20260504034557_quick_northstar", sql: m1 },
  { name: "20260504041009_bouncy_network", sql: m2 },
  { name: "20260504185448_aspiring_the_santerians", sql: m3 },
  { name: "20260504190033_new_maria_hill", sql: m4 },
  { name: "20260504190300_neat_shard", sql: m5 },
  { name: "20260504194132_sloppy_squadron_supreme", sql: m6 },
  { name: "20260504194244_solid_storm", sql: m7 },
  { name: "20260504194512_cute_peter_parker", sql: m8 },
  { name: "20260504203509_nice_bill_hollister", sql: m9 },
  { name: "20260504215116_certain_richard_fisk", sql: m10 },
  { name: "20260509000000_pg_chain_columns", sql: m11 },
  { name: "20260510120000_per_workspace_collections", sql: m12 },
  { name: "20260510130000_flow_layout", sql: m13 },
  { name: "20260510140000_scheduled_tasks", sql: m14 },
  { name: "20260510150000_folders_tenant_id", sql: m15 },
  { name: "20260510160000_roles_apikeys_tenant_id", sql: m16 },
  { name: "20260510170000_seed_tenant_roles", sql: m17 },
  { name: "20260511000000_api_key_role_scope", sql: m18 },
  { name: "20260511120000_app_user_pool", sql: m19 },
  { name: "20260511120000_email_templates_pg", sql: m20 },
  { name: "20260511130000_app_user_roles", sql: m21 },
  { name: "20260512000000_email_config", sql: m22 },
  { name: "20260513120000_collections_vectorize", sql: m23 },
  { name: "20260513140000_activity_response", sql: m24 },
  { name: "20260513200000_workspace_config", sql: m25 },
  { name: "20260516000000_saml_sso", sql: m26 },
  { name: "20260517000000_ldap_sso", sql: m27 },
  { name: "20260517100000_collection_default_sort", sql: m28 },
  { name: "20260517110000_collection_adopt", sql: m29 },
  { name: "20260517120000_collection_system_aliases", sql: m30 },
  { name: "20260517130000_collection_soft_delete", sql: m31 },
  { name: "20260517130000_drop_site_name_setting", sql: m32 },
  { name: "20260520000000_shared_links", sql: m33 },
  { name: "20260520190000_workspace_theme_colors", sql: m34 },
  { name: "20260522120000_user_locale_timezone", sql: m35 },
  { name: "20260525010000_api_keys_mcp_metadata", sql: m36 },
  { name: "20260601210000_integrations", sql: m37 },
  { name: "20260603120000_collections_soft_delete_singleton", sql: m38 },
  { name: "20260604120000_passkey_aaguid", sql: m39 },
  { name: "20260609120000_collections_audit_reads", sql: m40 },
  { name: "20260613120000_platform_sso", sql: m41 },
  { name: "20260618120000_two_factor", sql: m42 },
  { name: "20260620120000_push_messaging", sql: m43 },
  { name: "20260620130000_sms_messaging", sql: m44 },
  { name: "20260620150000_job_queue", sql: m45 },
  { name: "20260620160000_uploads", sql: m46 },
  { name: "20260620170000_feature_flags", sql: m47 },
  { name: "20260620180000_collections_fts", sql: m48 },
  { name: "20260620190000_managed_webhooks", sql: m49 },
  { name: "20260621000000_ai_config", sql: m50 },
  { name: "20260627000000_ai_agents", sql: m51 },
  { name: "20260628000000_request_spans", sql: m52 },
  { name: "20260628100000_dashboards", sql: m53 },
  { name: "20260630120000_schema_versions", sql: m54 },
  { name: "20260701120000_sessions_created_idx", sql: m55 },
  { name: "20260702120000_activity_tenant_created_idx", sql: m56 },
  { name: "20260702130000_embeddings_per_model", sql: m57 },
  { name: "20260702150000_collection_pk_type", sql: m58 },
  { name: "20260703090000_external_migration", sql: m59 },
  { name: "20260704090000_collection_grouping", sql: m60 },
];
