import { Hono } from "hono";
import { z } from "zod";
import { AppError, type AuthSubject } from "@workeros/core";
import type { AppBindings } from "../app";
import { dispatchRpc } from "../services/sandbox/host-bridge";
import type { RpcOp } from "../services/sandbox/types";

const Body = z.object({
  op: z.enum(["fetch", "db.list", "db.one", "email.send"]),
  args: z.unknown().optional(),
  auth: z.object({
    userId: z.string().nullable(),
    email: z.string().nullable(),
    roles: z.array(z.string()),
  }),
});

/**
 * Internal endpoint used **only** by the `remote-http` executor service to
 * proxy `ctx.fetch / ctx.db / ctx.email` calls back into the main app.
 *
 * Authentication: shared-secret bearer token (`env.SANDBOX_RPC_TOKEN`). The
 * token is generated by the operator and configured on both the main app
 * (env) and the executor (the main app forwards it in the `/run` body so the
 * executor can include it in its callbacks).
 *
 * The `auth` field in the body is the impersonated user — it was sent from
 * main to executor as part of the original invocation, so we trust the
 * channel. The token gate is the only thing keeping a third party from
 * forging this payload.
 */
export const sandboxRpcRoutes = new Hono<AppBindings>().post("/", async (c) => {
  const ctx = c.get("ctx");
  const expected = ctx.env.SANDBOX_RPC_TOKEN;
  if (!expected) {
    throw new AppError(
      "FORBIDDEN",
      "SANDBOX_RPC_TOKEN is not configured; sandbox RPC disabled",
    );
  }
  const auth = c.req.header("authorization") ?? "";
  if (auth !== `Bearer ${expected}`) {
    throw new AppError("UNAUTHORIZED", "invalid sandbox RPC token");
  }

  const body = Body.parse(await c.req.json());
  const subject: AuthSubject = body.auth;

  try {
    const value = await dispatchRpc(
      { ctx, auth: subject },
      body.op as RpcOp,
      body.args,
    );
    return c.json({ ok: true, value });
  } catch (e) {
    return c.json(
      { ok: false, error: (e as Error).message },
      // 200 from the HTTP perspective — the executor still got an answer.
      // The {ok: false} body is what its proxy turns into a thrown Error.
      200,
    );
  }
});
