/**
 * Tell TypeScript that `.sql` files imported with `with { type: "text" }`
 * resolve to a `string`. Bun's bundler inlines the file contents at build
 * time across every runtime target we ship, so the runtime contract is
 * just "this is a string of SQL text".
 *
 * Used by `migrations-bundle.ts` (auto-generated by
 * `scripts/gen-migration-bundles.ts`) so the boot-time auto-migrate
 * runner can carry every migration's SQL inside the function bundle
 * without runtime fs lookups.
 */
declare module "*.sql" {
  const content: string;
  export default content;
}
