/**
 * Lingui catalog integrity tests for the admin SPA translation.
 *
 * These guard the `.po` catalogs under `src/client/locales/*` — they are
 * generated by `bun run i18n:extract` and hand/auto-translated, so they can
 * drift out of sync with each other. Pure file parsing; no DB harness needed.
 *
 * Checks, per non-source locale:
 *  - the msgid set matches the `en` source exactly (no missing / stale keys);
 *  - every message is translated (no empty `msgstr`);
 *  - interpolation placeholders (`{name}`) and nested-element tags (`<0>`)
 *    are preserved exactly — a dropped placeholder is a runtime crash.
 */
import { describe, test, expect } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const LOCALES_DIR = join(import.meta.dir, "../src/client/locales");
/** Non-source locales that ship a catalog. Keep in sync with lingui.config. */
const TARGET_LOCALES = ["tr"];

/** Minimal gettext `.po` parser → Map<msgid, msgstr> (header entry dropped). */
function parsePo(text: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const block of text.split("\n\n")) {
    if (!block.trim()) continue;
    let mode: "id" | "str" | null = null;
    let id = "";
    let str = "";
    for (const line of block.split("\n")) {
      if (line.startsWith("#")) continue;
      const mId = /^msgid\s+"(.*)"$/.exec(line);
      const mStr = /^msgstr\s+"(.*)"$/.exec(line);
      const mCont = /^"(.*)"$/.exec(line);
      if (mId) {
        mode = "id";
        id += mId[1];
      } else if (mStr) {
        mode = "str";
        str += mStr[1];
      } else if (mCont) {
        if (mode === "id") id += mCont[1];
        else if (mode === "str") str += mCont[1];
      }
    }
    if (id !== "") out.set(id, str);
  }
  return out;
}

/** Placeholders + nested-element tags that must survive translation. */
function tokens(s: string): string[] {
  return [
    ...(s.match(/\{[^}]*\}/g) ?? []),
    ...(s.match(/<\/?\d+\/?>/g) ?? []),
  ].sort();
}

const readCatalog = (locale: string): Map<string, string> =>
  parsePo(readFileSync(join(LOCALES_DIR, locale, "messages.po"), "utf-8"));

const CLIENT_DIR = join(import.meta.dir, "../src/client");

/** Every `.ts`/`.tsx` under the admin SPA, minus the catalogs themselves. */
const clientSources = (dir: string, out: string[] = []): string[] => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== "locales") clientSources(p, out);
    } else if (/\.tsx?$/.test(entry.name)) {
      out.push(p);
    }
  }
  return out;
};

/**
 * Comments out, so a doc comment mentioning the `t` macro in backticks is not
 * read as a call to it. That is not hypothetical — several files here explain
 * how the macro works, and the closing backtick of an inline `t` reference
 * followed by any later backtick looks exactly like a tagged template.
 */
const stripComments = (src: string): string =>
  src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/[^\n]*/g, "$1");

/** `.po` escapes; the source literal is the unescaped form. */
const unescapePo = (s: string): string =>
  s.replace(/\\"/g, '"').replace(/\\\\/g, "\\").replace(/\\n/g, "\n");

describe("admin i18n catalogs", () => {
  const en = readCatalog("en");

  test("source catalog is non-empty", () => {
    expect(en.size).toBeGreaterThan(0);
  });

  /**
   * The gap the other checks structurally cannot see.
   *
   * Everything below compares `tr` against `en` — but `en` is itself GENERATED
   * by `bun run i18n:extract`. A string added to a component without running
   * extraction is in neither catalog, so it is missing from no comparison and
   * every check passes. Two strings shipped that way in `42cf2c8c` and the
   * full suite was green; they only surfaced when somebody else ran extract.
   *
   * So this reads the source instead. Restricted to non-interpolated
   * `` t`…` `` literals on one line: an interpolated one becomes `{0}` / `{name}`
   * in the catalog and matching that would need the macro itself, and
   * `<Trans>` bodies are JSX rather than text. Those are the cases this cannot
   * cover — it covers the one that actually bit.
   */
  test("every plain `t` literal in the source is in the en catalog", () => {
    const ids = new Set([...en.keys()].map(unescapePo));
    const missing: string[] = [];
    for (const file of clientSources(CLIENT_DIR)) {
      const src = stripComments(readFileSync(file, "utf-8"));
      // Not preceded by a backtick, word char or dot — so `` `t` `` in prose
      // and `foo.t\`…\`` are both excluded.
      for (const m of src.matchAll(/(^|[^`\w.])t`([^`$\\]*)`/g)) {
        const literal = m[2]!;
        if (!literal.trim() || literal.includes("\n")) continue;
        if (!ids.has(literal)) {
          missing.push(`${file.slice(file.indexOf("src/client/"))}: ${literal.slice(0, 60)}`);
        }
      }
    }
    expect(missing).toEqual([]);
  });

  for (const locale of TARGET_LOCALES) {
    describe(`locale: ${locale}`, () => {
      const cat = readCatalog(locale);

      test("msgid set matches the en source", () => {
        const missing = [...en.keys()].filter((k) => !cat.has(k));
        const stale = [...cat.keys()].filter((k) => !en.has(k));
        expect({ missing, stale }).toEqual({ missing: [], stale: [] });
      });

      test("every message is translated (no empty msgstr)", () => {
        const untranslated = [...cat.entries()]
          .filter(([, v]) => v.trim() === "")
          .map(([k]) => k);
        expect(untranslated).toEqual([]);
      });

      // A translation may *omit* a source placeholder — Turkish drops the
      // English plural-suffix arg (`{1}` in `user{1}`) since nouns aren't
      // pluralised after a number. But it must never *introduce* a
      // placeholder absent from the source: that resolves to `undefined`
      // at runtime. So the check is a subset, not an equality.
      test("translations introduce no unknown placeholders", () => {
        const broken: string[] = [];
        for (const [id, source] of en) {
          const translated = cat.get(id);
          if (!translated) continue;
          const allowed = new Set(tokens(source));
          const foreign = tokens(translated).filter((tk) => !allowed.has(tk));
          if (foreign.length) broken.push(`${id} → ${foreign.join(", ")}`);
        }
        expect(broken).toEqual([]);
      });
    });
  }
});
