/**
 * Lingui catalog integrity tests for the admin SPA translation.
 *
 * These guard the `.po` catalogs under `src/client/locales/*` — they are
 * generated by `bun run i18n:extract` and hand/auto-translated, so they can
 * drift out of sync with each other. Pure file parsing; no DB harness needed.
 *
 * Checks, per non-source locale:
 *  - the msgid set matches the `en` source exactly (no missing / stale keys);
 *  - every message is translated (no empty `msgstr`);
 *  - interpolation placeholders (`{name}`) and nested-element tags (`<0>`)
 *    are preserved exactly — a dropped placeholder is a runtime crash.
 */
import { describe, test, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const LOCALES_DIR = join(import.meta.dir, "../src/client/locales");
/** Non-source locales that ship a catalog. Keep in sync with lingui.config. */
const TARGET_LOCALES = ["tr"];

/** Minimal gettext `.po` parser → Map<msgid, msgstr> (header entry dropped). */
function parsePo(text: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const block of text.split("\n\n")) {
    if (!block.trim()) continue;
    let mode: "id" | "str" | null = null;
    let id = "";
    let str = "";
    for (const line of block.split("\n")) {
      if (line.startsWith("#")) continue;
      const mId = /^msgid\s+"(.*)"$/.exec(line);
      const mStr = /^msgstr\s+"(.*)"$/.exec(line);
      const mCont = /^"(.*)"$/.exec(line);
      if (mId) {
        mode = "id";
        id += mId[1];
      } else if (mStr) {
        mode = "str";
        str += mStr[1];
      } else if (mCont) {
        if (mode === "id") id += mCont[1];
        else if (mode === "str") str += mCont[1];
      }
    }
    if (id !== "") out.set(id, str);
  }
  return out;
}

/** Placeholders + nested-element tags that must survive translation. */
function tokens(s: string): string[] {
  return [
    ...(s.match(/\{[^}]*\}/g) ?? []),
    ...(s.match(/<\/?\d+\/?>/g) ?? []),
  ].sort();
}

const readCatalog = (locale: string): Map<string, string> =>
  parsePo(readFileSync(join(LOCALES_DIR, locale, "messages.po"), "utf-8"));

describe("admin i18n catalogs", () => {
  const en = readCatalog("en");

  test("source catalog is non-empty", () => {
    expect(en.size).toBeGreaterThan(0);
  });

  for (const locale of TARGET_LOCALES) {
    describe(`locale: ${locale}`, () => {
      const cat = readCatalog(locale);

      test("msgid set matches the en source", () => {
        const missing = [...en.keys()].filter((k) => !cat.has(k));
        const stale = [...cat.keys()].filter((k) => !en.has(k));
        expect({ missing, stale }).toEqual({ missing: [], stale: [] });
      });

      test("every message is translated (no empty msgstr)", () => {
        const untranslated = [...cat.entries()]
          .filter(([, v]) => v.trim() === "")
          .map(([k]) => k);
        expect(untranslated).toEqual([]);
      });

      // A translation may *omit* a source placeholder — Turkish drops the
      // English plural-suffix arg (`{1}` in `user{1}`) since nouns aren't
      // pluralised after a number. But it must never *introduce* a
      // placeholder absent from the source: that resolves to `undefined`
      // at runtime. So the check is a subset, not an equality.
      test("translations introduce no unknown placeholders", () => {
        const broken: string[] = [];
        for (const [id, source] of en) {
          const translated = cat.get(id);
          if (!translated) continue;
          const allowed = new Set(tokens(source));
          const foreign = tokens(translated).filter((tk) => !allowed.has(tk));
          if (foreign.length) broken.push(`${id} → ${foreign.join(", ")}`);
        }
        expect(broken).toEqual([]);
      });
    });
  }
});
