/* eslint-disable */
// AUTO-GENERATED by scripts/gen-migration-bundles.ts — do not edit by hand.
// Run `bun scripts/gen-migration-bundles.ts` after adding a migration to
// regenerate. The CI hook will fail if this file is out of sync.

import m0 from "../../drizzle/sqlite/20260503204108_nappy_ares/migration.sql" with { type: "text" };
import m1 from "../../drizzle/sqlite/20260504034356_warm_stone_men/migration.sql" with { type: "text" };
import m2 from "../../drizzle/sqlite/20260504041008_white_reavers/migration.sql" with { type: "text" };
import m3 from "../../drizzle/sqlite/20260504185447_green_captain_flint/migration.sql" with { type: "text" };
import m4 from "../../drizzle/sqlite/20260504190032_massive_william_stryker/migration.sql" with { type: "text" };
import m5 from "../../drizzle/sqlite/20260504190259_overconfident_misty_knight/migration.sql" with { type: "text" };
import m6 from "../../drizzle/sqlite/20260504194131_rich_old_lace/migration.sql" with { type: "text" };
import m7 from "../../drizzle/sqlite/20260504194243_petite_queen_noir/migration.sql" with { type: "text" };
import m8 from "../../drizzle/sqlite/20260504194511_sweet_stature/migration.sql" with { type: "text" };
import m9 from "../../drizzle/sqlite/20260504203508_rapid_jamie_braddock/migration.sql" with { type: "text" };
import m10 from "../../drizzle/sqlite/20260504215202_condemned_hedge_knight/migration.sql" with { type: "text" };
import m11 from "../../drizzle/sqlite/20260506045054_sour_ma_gnuci/migration.sql" with { type: "text" };
import m12 from "../../drizzle/sqlite/20260506050714_material_ironclad/migration.sql" with { type: "text" };
import m13 from "../../drizzle/sqlite/20260506051054_clear_penance/migration.sql" with { type: "text" };
import m14 from "../../drizzle/sqlite/20260509212015_talented_machine_man/migration.sql" with { type: "text" };
import m15 from "../../drizzle/sqlite/20260509222951_noisy_sir_ram/migration.sql" with { type: "text" };
import m16 from "../../drizzle/sqlite/20260509233120_robust_orphan/migration.sql" with { type: "text" };
import m17 from "../../drizzle/sqlite/20260510000855_many_prism/migration.sql" with { type: "text" };
import m18 from "../../drizzle/sqlite/20260510120000_per_workspace_collections/migration.sql" with { type: "text" };
import m19 from "../../drizzle/sqlite/20260510130000_flow_layout/migration.sql" with { type: "text" };
import m20 from "../../drizzle/sqlite/20260510140000_scheduled_tasks/migration.sql" with { type: "text" };
import m21 from "../../drizzle/sqlite/20260510150000_folders_tenant_id/migration.sql" with { type: "text" };
import m22 from "../../drizzle/sqlite/20260510160000_roles_apikeys_tenant_id/migration.sql" with { type: "text" };
import m23 from "../../drizzle/sqlite/20260510170000_seed_tenant_roles/migration.sql" with { type: "text" };
import m24 from "../../drizzle/sqlite/20260511000000_api_key_role_scope/migration.sql" with { type: "text" };
import m25 from "../../drizzle/sqlite/20260511120000_app_user_pool/migration.sql" with { type: "text" };
import m26 from "../../drizzle/sqlite/20260511130000_app_user_roles/migration.sql" with { type: "text" };
import m27 from "../../drizzle/sqlite/20260512000000_email_config/migration.sql" with { type: "text" };
import m28 from "../../drizzle/sqlite/20260513120000_collections_vectorize/migration.sql" with { type: "text" };
import m29 from "../../drizzle/sqlite/20260513140000_activity_response/migration.sql" with { type: "text" };
import m30 from "../../drizzle/sqlite/20260513200000_workspace_config/migration.sql" with { type: "text" };
import m31 from "../../drizzle/sqlite/20260516000000_saml_sso/migration.sql" with { type: "text" };
import m32 from "../../drizzle/sqlite/20260517000000_ldap_sso/migration.sql" with { type: "text" };
import m33 from "../../drizzle/sqlite/20260517100000_collection_default_sort/migration.sql" with { type: "text" };
import m34 from "../../drizzle/sqlite/20260517110000_collection_adopt/migration.sql" with { type: "text" };
import m35 from "../../drizzle/sqlite/20260517120000_collection_system_aliases/migration.sql" with { type: "text" };
import m36 from "../../drizzle/sqlite/20260517130000_collection_soft_delete/migration.sql" with { type: "text" };
import m37 from "../../drizzle/sqlite/20260517130000_drop_site_name_setting/migration.sql" with { type: "text" };
import m38 from "../../drizzle/sqlite/20260520000000_shared_links/migration.sql" with { type: "text" };
import m39 from "../../drizzle/sqlite/20260520190000_workspace_theme_colors/migration.sql" with { type: "text" };
import m40 from "../../drizzle/sqlite/20260522120000_user_locale_timezone/migration.sql" with { type: "text" };
import m41 from "../../drizzle/sqlite/20260525010000_api_keys_mcp_metadata/migration.sql" with { type: "text" };
import m42 from "../../drizzle/sqlite/20260601210000_integrations/migration.sql" with { type: "text" };
import m43 from "../../drizzle/sqlite/20260603120000_collections_soft_delete_singleton/migration.sql" with { type: "text" };
import m44 from "../../drizzle/sqlite/20260604120000_passkey_aaguid/migration.sql" with { type: "text" };
import m45 from "../../drizzle/sqlite/20260609120000_collections_audit_reads/migration.sql" with { type: "text" };
import m46 from "../../drizzle/sqlite/20260613120000_platform_sso/migration.sql" with { type: "text" };
import m47 from "../../drizzle/sqlite/20260617120000_embedding_vectors/migration.sql" with { type: "text" };
import m48 from "../../drizzle/sqlite/20260618120000_two_factor/migration.sql" with { type: "text" };
import m49 from "../../drizzle/sqlite/20260620120000_push_messaging/migration.sql" with { type: "text" };
import m50 from "../../drizzle/sqlite/20260620130000_sms_messaging/migration.sql" with { type: "text" };
import m51 from "../../drizzle/sqlite/20260620150000_job_queue/migration.sql" with { type: "text" };
import m52 from "../../drizzle/sqlite/20260620160000_uploads/migration.sql" with { type: "text" };
import m53 from "../../drizzle/sqlite/20260620170000_feature_flags/migration.sql" with { type: "text" };
import m54 from "../../drizzle/sqlite/20260620180000_collections_fts/migration.sql" with { type: "text" };
import m55 from "../../drizzle/sqlite/20260620190000_managed_webhooks/migration.sql" with { type: "text" };
import m56 from "../../drizzle/sqlite/20260621000000_ai_config/migration.sql" with { type: "text" };
import m57 from "../../drizzle/sqlite/20260627000000_ai_agents/migration.sql" with { type: "text" };
import m58 from "../../drizzle/sqlite/20260628000000_request_spans/migration.sql" with { type: "text" };
import m59 from "../../drizzle/sqlite/20260628100000_dashboards/migration.sql" with { type: "text" };
import m60 from "../../drizzle/sqlite/20260630120000_schema_versions/migration.sql" with { type: "text" };
import m61 from "../../drizzle/sqlite/20260701120000_sessions_created_idx/migration.sql" with { type: "text" };
import m62 from "../../drizzle/sqlite/20260702120000_activity_tenant_created_idx/migration.sql" with { type: "text" };
import m63 from "../../drizzle/sqlite/20260702150000_collection_pk_type/migration.sql" with { type: "text" };
import m64 from "../../drizzle/sqlite/20260703090000_external_migration/migration.sql" with { type: "text" };
import m65 from "../../drizzle/sqlite/20260704090000_collection_grouping/migration.sql" with { type: "text" };
import m66 from "../../drizzle/sqlite/20260714090000_collection_kanban_group_by/migration.sql" with { type: "text" };
import m67 from "../../drizzle/sqlite/20260715090000_collection_kanban_action_map/migration.sql" with { type: "text" };
import m68 from "../../drizzle/sqlite/20260716090000_collections_presentation/migration.sql" with { type: "text" };
import m69 from "../../drizzle/sqlite/20260718090000_forms/migration.sql" with { type: "text" };
import m70 from "../../drizzle/sqlite/20260719090000_forms_stats/migration.sql" with { type: "text" };
import m71 from "../../drizzle/sqlite/20260720090000_usage_metering/migration.sql" with { type: "text" };
import m72 from "../../drizzle/sqlite/20260720120000_mcp_oauth/migration.sql" with { type: "text" };
import m73 from "../../drizzle/sqlite/20260721090000_extensions/migration.sql" with { type: "text" };
import m74 from "../../drizzle/sqlite/20260722090000_staged_edits/migration.sql" with { type: "text" };
import m75 from "../../drizzle/sqlite/20260725090000_agent_message_author/migration.sql" with { type: "text" };
import m76 from "../../drizzle/sqlite/20260725120000_agent_effort/migration.sql" with { type: "text" };
import m77 from "../../drizzle/sqlite/20260725150000_agent_rooms/migration.sql" with { type: "text" };
import m78 from "../../drizzle/sqlite/20260727090000_app_orgs/migration.sql" with { type: "text" };
import m79 from "../../drizzle/sqlite/20260727090000_mcp_role_guards/migration.sql" with { type: "text" };
import m80 from "../../drizzle/sqlite/20260727090000_product_analytics/migration.sql" with { type: "text" };
import m81 from "../../drizzle/sqlite/20260727100000_agent_semantic_memory/migration.sql" with { type: "text" };
import m82 from "../../drizzle/sqlite/20260727120000_payments/migration.sql" with { type: "text" };
import m83 from "../../drizzle/sqlite/20260729120000_integration_deliveries/migration.sql" with { type: "text" };
import m84 from "../../drizzle/sqlite/20260729140000_oidc_providers/migration.sql" with { type: "text" };
import m85 from "../../drizzle/sqlite/20260730090000_scim_config/migration.sql" with { type: "text" };
import m86 from "../../drizzle/sqlite/20260730120000_sync_hooks/migration.sql" with { type: "text" };
import m87 from "../../drizzle/sqlite/20260730150000_integration_oauth_states/migration.sql" with { type: "text" };
import m88 from "../../drizzle/sqlite/20260730160000_integration_syncs/migration.sql" with { type: "text" };
import m89 from "../../drizzle/sqlite/20260730180000_erasure_requests/migration.sql" with { type: "text" };
import m90 from "../../drizzle/sqlite/20260730190000_integration_syncs_direction/migration.sql" with { type: "text" };
import m91 from "../../drizzle/sqlite/20260801200000_document_templates/migration.sql" with { type: "text" };
import m92 from "../../drizzle/sqlite/20260802100000_signature_requests/migration.sql" with { type: "text" };
import m93 from "../../drizzle/sqlite/20260802160000_bookings/migration.sql" with { type: "text" };
import m94 from "../../drizzle/sqlite/20260803100000_approval_requests/migration.sql" with { type: "text" };
import m95 from "../../drizzle/sqlite/20260803140000_flow_schedule_fires/migration.sql" with { type: "text" };
import m96 from "../../drizzle/sqlite/20260803160000_sequences/migration.sql" with { type: "text" };
import m97 from "../../drizzle/sqlite/20260805100000_kpis/migration.sql" with { type: "text" };
import m98 from "../../drizzle/sqlite/20260805170000_kpi_alerts/migration.sql" with { type: "text" };
import m99 from "../../drizzle/sqlite/20260806100000_kpi_pins/migration.sql" with { type: "text" };
import m100 from "../../drizzle/sqlite/20260806180000_booking_settings/migration.sql" with { type: "text" };
import m101 from "../../drizzle/sqlite/20260807120000_form_invites/migration.sql" with { type: "text" };
import m102 from "../../drizzle/sqlite/20260807160000_form_drafts/migration.sql" with { type: "text" };
import m103 from "../../drizzle/sqlite/20260808090000_form_invite_reminders/migration.sql" with { type: "text" };
import m104 from "../../drizzle/sqlite/20260808120000_booking_records_collection/migration.sql" with { type: "text" };
import m105 from "../../drizzle/sqlite/20260808170000_role_org_assignable/migration.sql" with { type: "text" };
import m106 from "../../drizzle/sqlite/20260809080000_webhook_payload_fields/migration.sql" with { type: "text" };
import m107 from "../../drizzle/sqlite/20260809140000_third_party_auth/migration.sql" with { type: "text" };
import m108 from "../../drizzle/sqlite/20260809180000_auth_hooks/migration.sql" with { type: "text" };
import m109 from "../../drizzle/sqlite/20260810090000_broadcast_channels/migration.sql" with { type: "text" };
import m110 from "../../drizzle/sqlite/20260810140000_s3_credentials/migration.sql" with { type: "text" };
import m111 from "../../drizzle/sqlite/20260811090000_captcha_impersonation/migration.sql" with { type: "text" };
import m112 from "../../drizzle/sqlite/20260811140000_signing_keys/migration.sql" with { type: "text" };
import m113 from "../../drizzle/sqlite/20260812090000_cdc_sinks/migration.sql" with { type: "text" };
import m114 from "../../drizzle/sqlite/20260813090000_integration_child_mappings/migration.sql" with { type: "text" };
import m115 from "../../drizzle/sqlite/20260813100000_integration_task_runs/migration.sql" with { type: "text" };
import m116 from "../../drizzle/sqlite/20260813110000_integration_webhooks/migration.sql" with { type: "text" };
import m117 from "../../drizzle/sqlite/20260813120000_integration_listings/migration.sql" with { type: "text" };
import m118 from "../../drizzle/sqlite/20260813130000_resilience_retention/migration.sql" with { type: "text" };
import m119 from "../../drizzle/sqlite/20260814140000_ai_usage_counters/migration.sql" with { type: "text" };
import m120 from "../../drizzle/sqlite/20260814150000_agent_app_access/migration.sql" with { type: "text" };

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { name: "20260503204108_nappy_ares", sql: m0 },
  { name: "20260504034356_warm_stone_men", sql: m1 },
  { name: "20260504041008_white_reavers", sql: m2 },
  { name: "20260504185447_green_captain_flint", sql: m3 },
  { name: "20260504190032_massive_william_stryker", sql: m4 },
  { name: "20260504190259_overconfident_misty_knight", sql: m5 },
  { name: "20260504194131_rich_old_lace", sql: m6 },
  { name: "20260504194243_petite_queen_noir", sql: m7 },
  { name: "20260504194511_sweet_stature", sql: m8 },
  { name: "20260504203508_rapid_jamie_braddock", sql: m9 },
  { name: "20260504215202_condemned_hedge_knight", sql: m10 },
  { name: "20260506045054_sour_ma_gnuci", sql: m11 },
  { name: "20260506050714_material_ironclad", sql: m12 },
  { name: "20260506051054_clear_penance", sql: m13 },
  { name: "20260509212015_talented_machine_man", sql: m14 },
  { name: "20260509222951_noisy_sir_ram", sql: m15 },
  { name: "20260509233120_robust_orphan", sql: m16 },
  { name: "20260510000855_many_prism", sql: m17 },
  { name: "20260510120000_per_workspace_collections", sql: m18 },
  { name: "20260510130000_flow_layout", sql: m19 },
  { name: "20260510140000_scheduled_tasks", sql: m20 },
  { name: "20260510150000_folders_tenant_id", sql: m21 },
  { name: "20260510160000_roles_apikeys_tenant_id", sql: m22 },
  { name: "20260510170000_seed_tenant_roles", sql: m23 },
  { name: "20260511000000_api_key_role_scope", sql: m24 },
  { name: "20260511120000_app_user_pool", sql: m25 },
  { name: "20260511130000_app_user_roles", sql: m26 },
  { name: "20260512000000_email_config", sql: m27 },
  { name: "20260513120000_collections_vectorize", sql: m28 },
  { name: "20260513140000_activity_response", sql: m29 },
  { name: "20260513200000_workspace_config", sql: m30 },
  { name: "20260516000000_saml_sso", sql: m31 },
  { name: "20260517000000_ldap_sso", sql: m32 },
  { name: "20260517100000_collection_default_sort", sql: m33 },
  { name: "20260517110000_collection_adopt", sql: m34 },
  { name: "20260517120000_collection_system_aliases", sql: m35 },
  { name: "20260517130000_collection_soft_delete", sql: m36 },
  { name: "20260517130000_drop_site_name_setting", sql: m37 },
  { name: "20260520000000_shared_links", sql: m38 },
  { name: "20260520190000_workspace_theme_colors", sql: m39 },
  { name: "20260522120000_user_locale_timezone", sql: m40 },
  { name: "20260525010000_api_keys_mcp_metadata", sql: m41 },
  { name: "20260601210000_integrations", sql: m42 },
  { name: "20260603120000_collections_soft_delete_singleton", sql: m43 },
  { name: "20260604120000_passkey_aaguid", sql: m44 },
  { name: "20260609120000_collections_audit_reads", sql: m45 },
  { name: "20260613120000_platform_sso", sql: m46 },
  { name: "20260617120000_embedding_vectors", sql: m47 },
  { name: "20260618120000_two_factor", sql: m48 },
  { name: "20260620120000_push_messaging", sql: m49 },
  { name: "20260620130000_sms_messaging", sql: m50 },
  { name: "20260620150000_job_queue", sql: m51 },
  { name: "20260620160000_uploads", sql: m52 },
  { name: "20260620170000_feature_flags", sql: m53 },
  { name: "20260620180000_collections_fts", sql: m54 },
  { name: "20260620190000_managed_webhooks", sql: m55 },
  { name: "20260621000000_ai_config", sql: m56 },
  { name: "20260627000000_ai_agents", sql: m57 },
  { name: "20260628000000_request_spans", sql: m58 },
  { name: "20260628100000_dashboards", sql: m59 },
  { name: "20260630120000_schema_versions", sql: m60 },
  { name: "20260701120000_sessions_created_idx", sql: m61 },
  { name: "20260702120000_activity_tenant_created_idx", sql: m62 },
  { name: "20260702150000_collection_pk_type", sql: m63 },
  { name: "20260703090000_external_migration", sql: m64 },
  { name: "20260704090000_collection_grouping", sql: m65 },
  { name: "20260714090000_collection_kanban_group_by", sql: m66 },
  { name: "20260715090000_collection_kanban_action_map", sql: m67 },
  { name: "20260716090000_collections_presentation", sql: m68 },
  { name: "20260718090000_forms", sql: m69 },
  { name: "20260719090000_forms_stats", sql: m70 },
  { name: "20260720090000_usage_metering", sql: m71 },
  { name: "20260720120000_mcp_oauth", sql: m72 },
  { name: "20260721090000_extensions", sql: m73 },
  { name: "20260722090000_staged_edits", sql: m74 },
  { name: "20260725090000_agent_message_author", sql: m75 },
  { name: "20260725120000_agent_effort", sql: m76 },
  { name: "20260725150000_agent_rooms", sql: m77 },
  { name: "20260727090000_app_orgs", sql: m78 },
  { name: "20260727090000_mcp_role_guards", sql: m79 },
  { name: "20260727090000_product_analytics", sql: m80 },
  { name: "20260727100000_agent_semantic_memory", sql: m81 },
  { name: "20260727120000_payments", sql: m82 },
  { name: "20260729120000_integration_deliveries", sql: m83 },
  { name: "20260729140000_oidc_providers", sql: m84 },
  { name: "20260730090000_scim_config", sql: m85 },
  { name: "20260730120000_sync_hooks", sql: m86 },
  { name: "20260730150000_integration_oauth_states", sql: m87 },
  { name: "20260730160000_integration_syncs", sql: m88 },
  { name: "20260730180000_erasure_requests", sql: m89 },
  { name: "20260730190000_integration_syncs_direction", sql: m90 },
  { name: "20260801200000_document_templates", sql: m91 },
  { name: "20260802100000_signature_requests", sql: m92 },
  { name: "20260802160000_bookings", sql: m93 },
  { name: "20260803100000_approval_requests", sql: m94 },
  { name: "20260803140000_flow_schedule_fires", sql: m95 },
  { name: "20260803160000_sequences", sql: m96 },
  { name: "20260805100000_kpis", sql: m97 },
  { name: "20260805170000_kpi_alerts", sql: m98 },
  { name: "20260806100000_kpi_pins", sql: m99 },
  { name: "20260806180000_booking_settings", sql: m100 },
  { name: "20260807120000_form_invites", sql: m101 },
  { name: "20260807160000_form_drafts", sql: m102 },
  { name: "20260808090000_form_invite_reminders", sql: m103 },
  { name: "20260808120000_booking_records_collection", sql: m104 },
  { name: "20260808170000_role_org_assignable", sql: m105 },
  { name: "20260809080000_webhook_payload_fields", sql: m106 },
  { name: "20260809140000_third_party_auth", sql: m107 },
  { name: "20260809180000_auth_hooks", sql: m108 },
  { name: "20260810090000_broadcast_channels", sql: m109 },
  { name: "20260810140000_s3_credentials", sql: m110 },
  { name: "20260811090000_captcha_impersonation", sql: m111 },
  { name: "20260811140000_signing_keys", sql: m112 },
  { name: "20260812090000_cdc_sinks", sql: m113 },
  { name: "20260813090000_integration_child_mappings", sql: m114 },
  { name: "20260813100000_integration_task_runs", sql: m115 },
  { name: "20260813110000_integration_webhooks", sql: m116 },
  { name: "20260813120000_integration_listings", sql: m117 },
  { name: "20260813130000_resilience_retention", sql: m118 },
  { name: "20260814140000_ai_usage_counters", sql: m119 },
  { name: "20260814150000_agent_app_access", sql: m120 },
];
