/* eslint-disable */
// AUTO-GENERATED by scripts/gen-migration-bundles.ts — do not edit by hand.
// Run `bun scripts/gen-migration-bundles.ts` after adding a migration to
// regenerate. The CI hook will fail if this file is out of sync.

import m0 from "../../drizzle/sqlite/20260503204108_nappy_ares/migration.sql" with { type: "text" };
import m1 from "../../drizzle/sqlite/20260504034356_warm_stone_men/migration.sql" with { type: "text" };
import m2 from "../../drizzle/sqlite/20260504041008_white_reavers/migration.sql" with { type: "text" };
import m3 from "../../drizzle/sqlite/20260504185447_green_captain_flint/migration.sql" with { type: "text" };
import m4 from "../../drizzle/sqlite/20260504190032_massive_william_stryker/migration.sql" with { type: "text" };
import m5 from "../../drizzle/sqlite/20260504190259_overconfident_misty_knight/migration.sql" with { type: "text" };
import m6 from "../../drizzle/sqlite/20260504194131_rich_old_lace/migration.sql" with { type: "text" };
import m7 from "../../drizzle/sqlite/20260504194243_petite_queen_noir/migration.sql" with { type: "text" };
import m8 from "../../drizzle/sqlite/20260504194511_sweet_stature/migration.sql" with { type: "text" };
import m9 from "../../drizzle/sqlite/20260504203508_rapid_jamie_braddock/migration.sql" with { type: "text" };
import m10 from "../../drizzle/sqlite/20260504215202_condemned_hedge_knight/migration.sql" with { type: "text" };
import m11 from "../../drizzle/sqlite/20260506045054_sour_ma_gnuci/migration.sql" with { type: "text" };
import m12 from "../../drizzle/sqlite/20260506050714_material_ironclad/migration.sql" with { type: "text" };
import m13 from "../../drizzle/sqlite/20260506051054_clear_penance/migration.sql" with { type: "text" };
import m14 from "../../drizzle/sqlite/20260509212015_talented_machine_man/migration.sql" with { type: "text" };
import m15 from "../../drizzle/sqlite/20260509222951_noisy_sir_ram/migration.sql" with { type: "text" };
import m16 from "../../drizzle/sqlite/20260509233120_robust_orphan/migration.sql" with { type: "text" };
import m17 from "../../drizzle/sqlite/20260510000855_many_prism/migration.sql" with { type: "text" };
import m18 from "../../drizzle/sqlite/20260510120000_per_workspace_collections/migration.sql" with { type: "text" };
import m19 from "../../drizzle/sqlite/20260510130000_flow_layout/migration.sql" with { type: "text" };
import m20 from "../../drizzle/sqlite/20260510140000_scheduled_tasks/migration.sql" with { type: "text" };
import m21 from "../../drizzle/sqlite/20260510150000_folders_tenant_id/migration.sql" with { type: "text" };
import m22 from "../../drizzle/sqlite/20260510160000_roles_apikeys_tenant_id/migration.sql" with { type: "text" };
import m23 from "../../drizzle/sqlite/20260510170000_seed_tenant_roles/migration.sql" with { type: "text" };
import m24 from "../../drizzle/sqlite/20260511000000_api_key_role_scope/migration.sql" with { type: "text" };
import m25 from "../../drizzle/sqlite/20260511120000_app_user_pool/migration.sql" with { type: "text" };
import m26 from "../../drizzle/sqlite/20260511130000_app_user_roles/migration.sql" with { type: "text" };
import m27 from "../../drizzle/sqlite/20260512000000_email_config/migration.sql" with { type: "text" };
import m28 from "../../drizzle/sqlite/20260513120000_collections_vectorize/migration.sql" with { type: "text" };
import m29 from "../../drizzle/sqlite/20260513140000_activity_response/migration.sql" with { type: "text" };
import m30 from "../../drizzle/sqlite/20260513200000_workspace_config/migration.sql" with { type: "text" };
import m31 from "../../drizzle/sqlite/20260516000000_saml_sso/migration.sql" with { type: "text" };
import m32 from "../../drizzle/sqlite/20260517000000_ldap_sso/migration.sql" with { type: "text" };
import m33 from "../../drizzle/sqlite/20260517100000_collection_default_sort/migration.sql" with { type: "text" };
import m34 from "../../drizzle/sqlite/20260517110000_collection_adopt/migration.sql" with { type: "text" };
import m35 from "../../drizzle/sqlite/20260517120000_collection_system_aliases/migration.sql" with { type: "text" };
import m36 from "../../drizzle/sqlite/20260517130000_collection_soft_delete/migration.sql" with { type: "text" };
import m37 from "../../drizzle/sqlite/20260517130000_drop_site_name_setting/migration.sql" with { type: "text" };
import m38 from "../../drizzle/sqlite/20260520000000_shared_links/migration.sql" with { type: "text" };
import m39 from "../../drizzle/sqlite/20260520190000_workspace_theme_colors/migration.sql" with { type: "text" };
import m40 from "../../drizzle/sqlite/20260522120000_user_locale_timezone/migration.sql" with { type: "text" };
import m41 from "../../drizzle/sqlite/20260525010000_api_keys_mcp_metadata/migration.sql" with { type: "text" };
import m42 from "../../drizzle/sqlite/20260601210000_integrations/migration.sql" with { type: "text" };
import m43 from "../../drizzle/sqlite/20260603120000_collections_soft_delete_singleton/migration.sql" with { type: "text" };
import m44 from "../../drizzle/sqlite/20260604120000_passkey_aaguid/migration.sql" with { type: "text" };
import m45 from "../../drizzle/sqlite/20260609120000_collections_audit_reads/migration.sql" with { type: "text" };

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { name: "20260503204108_nappy_ares", sql: m0 },
  { name: "20260504034356_warm_stone_men", sql: m1 },
  { name: "20260504041008_white_reavers", sql: m2 },
  { name: "20260504185447_green_captain_flint", sql: m3 },
  { name: "20260504190032_massive_william_stryker", sql: m4 },
  { name: "20260504190259_overconfident_misty_knight", sql: m5 },
  { name: "20260504194131_rich_old_lace", sql: m6 },
  { name: "20260504194243_petite_queen_noir", sql: m7 },
  { name: "20260504194511_sweet_stature", sql: m8 },
  { name: "20260504203508_rapid_jamie_braddock", sql: m9 },
  { name: "20260504215202_condemned_hedge_knight", sql: m10 },
  { name: "20260506045054_sour_ma_gnuci", sql: m11 },
  { name: "20260506050714_material_ironclad", sql: m12 },
  { name: "20260506051054_clear_penance", sql: m13 },
  { name: "20260509212015_talented_machine_man", sql: m14 },
  { name: "20260509222951_noisy_sir_ram", sql: m15 },
  { name: "20260509233120_robust_orphan", sql: m16 },
  { name: "20260510000855_many_prism", sql: m17 },
  { name: "20260510120000_per_workspace_collections", sql: m18 },
  { name: "20260510130000_flow_layout", sql: m19 },
  { name: "20260510140000_scheduled_tasks", sql: m20 },
  { name: "20260510150000_folders_tenant_id", sql: m21 },
  { name: "20260510160000_roles_apikeys_tenant_id", sql: m22 },
  { name: "20260510170000_seed_tenant_roles", sql: m23 },
  { name: "20260511000000_api_key_role_scope", sql: m24 },
  { name: "20260511120000_app_user_pool", sql: m25 },
  { name: "20260511130000_app_user_roles", sql: m26 },
  { name: "20260512000000_email_config", sql: m27 },
  { name: "20260513120000_collections_vectorize", sql: m28 },
  { name: "20260513140000_activity_response", sql: m29 },
  { name: "20260513200000_workspace_config", sql: m30 },
  { name: "20260516000000_saml_sso", sql: m31 },
  { name: "20260517000000_ldap_sso", sql: m32 },
  { name: "20260517100000_collection_default_sort", sql: m33 },
  { name: "20260517110000_collection_adopt", sql: m34 },
  { name: "20260517120000_collection_system_aliases", sql: m35 },
  { name: "20260517130000_collection_soft_delete", sql: m36 },
  { name: "20260517130000_drop_site_name_setting", sql: m37 },
  { name: "20260520000000_shared_links", sql: m38 },
  { name: "20260520190000_workspace_theme_colors", sql: m39 },
  { name: "20260522120000_user_locale_timezone", sql: m40 },
  { name: "20260525010000_api_keys_mcp_metadata", sql: m41 },
  { name: "20260601210000_integrations", sql: m42 },
  { name: "20260603120000_collections_soft_delete_singleton", sql: m43 },
  { name: "20260604120000_passkey_aaguid", sql: m44 },
  { name: "20260609120000_collections_audit_reads", sql: m45 },
];
