/**
 * Stock across every location, and the ledger behind it.
 *
 * An adjustment here writes BOTH halves deliberately: the level (what is true
 * now) and a `stock_movements` row (why it changed). A store that only moves
 * the level can never answer "where did forty units go", which is the first
 * question asked after a stock-take.
 */
import { useState } from "react";
import { inventoryLevels, locations, stockMovements } from "../lib/backlex";
import { errText, useAsync, useToast } from "../lib/hooks";
import { fmtDateTime, fmtNumber } from "../lib/money";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  ErrorNote,
  Field,
  Modal,
  PageHeader,
  Table,
  TableScroll,
  TableSkeleton,
  Td,
  Th,
  inputCls,
} from "../lib/ui";

export function Inventory() {
  const [locationId, setLocationId] = useState("");
  const [lowOnly, setLowOnly] = useState(false);
  const [adjusting, setAdjusting] = useState<{ levelId?: string; variantId: string; locationId: string; onHand: number } | null>(null);
  const toast = useToast();

  const locs = useAsync(() => locations.list({ limit: 100 }).then((r) => r.data), []);

  const data = useAsync(async () => {
    const levels = await inventoryLevels
      .list({
        filter: locationId ? { location: { _eq: locationId } } : undefined,
        limit: 200,
        expand: ["variant", "location"],
      })
      .then((r) => r.data);
    return levels;
  }, [locationId]);

  const movements = useAsync(
    () => stockMovements.list({ sort: ["-occurred_at"], limit: 25, expand: ["variant", "location"] }).then((r) => r.data),
    [],
  );

  const rows = (data.data ?? []).filter((l) => !lowOnly || (l.available ?? 0) <= (l.reorder_point ?? 0));

  return (
    <>
      <PageHeader title="Inventory" subtitle="On hand minus committed is generated by the database — nobody types it." />

      <Card className="mb-4">
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Location">
            <select className={inputCls} value={locationId} onChange={(e) => setLocationId(e.target.value)}>
              <option value="">All locations</option>
              {(locs.data ?? []).map((l) => (
                <option key={l.id} value={l.id}>
                  {l.name}
                </option>
              ))}
            </select>
          </Field>
          <label className="flex items-end gap-2 pb-1.5 text-sm">
            <input type="checkbox" checked={lowOnly} onChange={(e) => setLowOnly(e.target.checked)} />
            Only at or below the reorder point
          </label>
        </div>
      </Card>

      <Card className="mb-4">
        <ErrorNote error={data.error ? errText(data.error) : null} />
        {data.data == null ? (
          <TableSkeleton rows={8} cols={6} />
        ) : rows.length === 0 ? (
          <EmptyState title="Nothing stocked here" hint="Inventory is held per variant per location — add a level from a product's Inventory tab." />
        ) : (
          <TableScroll>
            <Table>
              <thead>
                <tr>
                  <Th>Variant</Th>
                  <Th>Location</Th>
                  <Th className="text-right">On hand</Th>
                  <Th className="text-right">Committed</Th>
                  <Th className="text-right">Available</Th>
                  <Th className="text-right">Incoming</Th>
                  <Th className="text-right">Reorder at</Th>
                  <Th />
                </tr>
              </thead>
              <tbody>
                {rows.map((l) => {
                  const v = l.variant as { id?: string; title?: string; sku?: string } | string | null;
                  const loc = l.location as { id?: string; name?: string } | string | null;
                  const low = (l.available ?? 0) <= (l.reorder_point ?? 0);
                  return (
                    <tr key={l.id} className="border-t border-white/5">
                      <Td className="font-medium">{(v && typeof v === "object" && (v.title || v.sku)) || "—"}</Td>
                      <Td className="text-white/60">{(loc && typeof loc === "object" && loc.name) || "—"}</Td>
                      <Td className="text-right tabular-nums">{fmtNumber(l.on_hand)}</Td>
                      <Td className="text-right tabular-nums text-white/60">{fmtNumber(l.committed)}</Td>
                      <Td className="text-right tabular-nums">
                        <Badge tone={low ? ((l.available ?? 0) <= 0 ? "red" : "amber") : "green"}>{l.available ?? 0}</Badge>
                      </Td>
                      <Td className="text-right tabular-nums text-white/50">{fmtNumber(l.incoming)}</Td>
                      <Td className="text-right tabular-nums text-white/50">{fmtNumber(l.reorder_point)}</Td>
                      <Td className="text-right">
                        <Button
                          onClick={() =>
                            setAdjusting({
                              levelId: l.id,
                              variantId: (v && typeof v === "object" && v.id) || String(l.variant),
                              locationId: (loc && typeof loc === "object" && loc.id) || String(l.location),
                              onHand: l.on_hand ?? 0,
                            })
                          }
                        >
                          Adjust
                        </Button>
                      </Td>
                    </tr>
                  );
                })}
              </tbody>
            </Table>
          </TableScroll>
        )}
      </Card>

      <Card>
        <h2 className="mb-3 font-medium">Recent movements</h2>
        {movements.data == null ? (
          <TableSkeleton rows={5} cols={5} />
        ) : movements.data.length === 0 ? (
          <p className="text-sm text-white/45">No movements recorded yet.</p>
        ) : (
          <TableScroll>
            <Table>
              <thead>
                <tr>
                  <Th>When</Th>
                  <Th>Variant</Th>
                  <Th>Location</Th>
                  <Th>Kind</Th>
                  <Th>Reference</Th>
                  <Th className="text-right">Qty</Th>
                </tr>
              </thead>
              <tbody>
                {movements.data.map((m) => {
                  const v = m.variant as { title?: string; sku?: string } | string | null;
                  const loc = m.location as { name?: string } | string | null;
                  return (
                    <tr key={m.id} className="border-t border-white/5">
                      <Td className="whitespace-nowrap text-white/50">{fmtDateTime(m.occurred_at)}</Td>
                      <Td>{(v && typeof v === "object" && (v.title || v.sku)) || "—"}</Td>
                      <Td className="text-white/60">{(loc && typeof loc === "object" && loc.name) || "—"}</Td>
                      <Td>
                        <Badge tone={(m.qty ?? 0) < 0 ? "amber" : "green"}>{m.movement_type ?? "—"}</Badge>
                      </Td>
                      <Td className="font-mono text-xs text-white/50">{m.reference ?? "—"}</Td>
                      <Td className={"text-right tabular-nums " + ((m.qty ?? 0) < 0 ? "text-red-300" : "text-emerald-300")}>
                        {(m.qty ?? 0) > 0 ? "+" : ""}
                        {m.qty ?? 0}
                      </Td>
                    </tr>
                  );
                })}
              </tbody>
            </Table>
          </TableScroll>
        )}
      </Card>

      {adjusting ? (
        <AdjustDialog
          target={adjusting}
          onClose={() => setAdjusting(null)}
          onDone={() => {
            setAdjusting(null);
            data.reload();
            movements.reload();
            toast("Stock adjusted and the movement recorded.");
          }}
        />
      ) : null}
    </>
  );
}

function AdjustDialog({
  target,
  onClose,
  onDone,
}: {
  target: { levelId?: string; variantId: string; locationId: string; onHand: number };
  onClose: () => void;
  onDone: () => void;
}) {
  const [delta, setDelta] = useState("0");
  const [kind, setKind] = useState("adjustment");
  const [reference, setReference] = useState("");
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");

  const next = target.onHand + Number(delta || 0);

  async function submit() {
    setBusy(true);
    setErr("");
    try {
      if (target.levelId) await inventoryLevels.update(target.levelId, { on_hand: next });
      else await inventoryLevels.create({ variant: target.variantId, location: target.locationId, on_hand: next, committed: 0 });
      await stockMovements.create({
        variant: target.variantId,
        location: target.locationId,
        movement_type: kind as "adjustment",
        qty: Number(delta || 0),
        reference: reference || undefined,
        note: note || undefined,
        occurred_at: Date.now(),
      });
      onDone();
    } catch (e) {
      setErr(errText(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal
      open
      onClose={onClose}
      title="Adjust stock"
      footer={
        <>
          <Button onClick={onClose}>Cancel</Button>
          <Button variant="primary" disabled={busy || Number(delta) === 0 || next < 0} onClick={submit}>
            {busy ? "Saving…" : `Set to ${next}`}
          </Button>
        </>
      }
    >
      {err ? <p className="mb-3 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">{err}</p> : null}
      <div className="grid gap-3 sm:grid-cols-2 [&>*]:min-w-0">
        <Field label="Change" hint={`${target.onHand} → ${next}`}>
          <input className={inputCls} type="number" value={delta} onChange={(e) => setDelta(e.target.value)} />
        </Field>
        <Field label="Kind">
          <select className={inputCls} value={kind} onChange={(e) => setKind(e.target.value)}>
            {["receipt", "sale", "return", "adjustment", "transfer", "shrinkage"].map((k) => (
              <option key={k} value={k}>
                {k}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Reference" hint="PO number, count sheet, order number.">
          <input className={inputCls} value={reference} onChange={(e) => setReference(e.target.value)} />
        </Field>
        <Field label="Note">
          <input className={inputCls} value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
      </div>
      {next < 0 ? <p className="mt-3 text-sm text-red-300">On hand cannot go below zero.</p> : null}
    </Modal>
  );
}
