import { writeFileSync } from "node:fs";

interface Field {
  name: string;
  type:
    | "text"
    | "longtext"
    | "integer"
    | "number"
    | "boolean"
    | "json"
    | "timestamp"
    | "uuid";
  required?: boolean;
}

interface Collection {
  slug: string;
  singular?: string | null;
  fields: Field[];
  ownerScoped: boolean | number;
}

const TS_TYPES: Record<Field["type"], string> = {
  text: "string",
  longtext: "string",
  integer: "number",
  number: "number",
  boolean: "boolean",
  json: "unknown",
  timestamp: "string",
  uuid: "string",
};

const pascal = (s: string): string =>
  s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());

const camel = (s: string): string =>
  s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());

const renderCollection = (c: Collection): string => {
  const lines: string[] = [];
  lines.push(`export interface ${pascal(c.slug)} {`);
  lines.push(`  id: string;`);
  if (c.ownerScoped) {
    lines.push(`  ownerId: string | null;`);
  }
  lines.push(`  createdAt: string;`);
  lines.push(`  updatedAt: string;`);
  for (const f of c.fields) {
    const t = TS_TYPES[f.type];
    const opt = f.required ? "" : " | null";
    lines.push(`  ${camel(f.name)}: ${t}${opt};`);
  }
  lines.push(`}`);
  return lines.join("\n");
};

const renderRegistry = (collections: Collection[]): string => {
  const entries = collections
    .map((c) => `  ${c.slug}: ${pascal(c.slug)};`)
    .join("\n");
  return `export interface Collections {\n${entries}\n}`;
};

export const runGenTypes = async (
  apiUrl: string,
  outPath?: string,
  apiKey?: string,
): Promise<void> => {
  const headers: Record<string, string> = {};
  if (apiKey) headers.authorization = `Bearer ${apiKey}`;
  const res = await fetch(`${apiUrl}/api/collections`, { headers });
  if (!res.ok) {
    throw new Error(`fetch ${apiUrl}/api/collections → ${res.status}`);
  }
  const body = (await res.json()) as { data: Collection[] };
  const banner = `// Auto-generated by \`backlex gen-types\` from ${apiUrl}\n// Do not edit by hand. Regenerate after schema changes.\n\n`;
  const out =
    banner +
    body.data.map(renderCollection).join("\n\n") +
    "\n\n" +
    renderRegistry(body.data) +
    "\n";

  if (outPath) {
    writeFileSync(outPath, out, "utf8");
    console.log(`✓ wrote ${body.data.length} collection(s) → ${outPath}`);
  } else {
    process.stdout.write(out);
  }
};
