import { writeFileSync } from "node:fs";

// Mirrors `FieldType` in `@backlex/core` (packages/db/src/field-types.ts).
type FieldType =
  | "text"
  | "longtext"
  | "integer"
  | "number"
  | "boolean"
  | "json"
  | "timestamp"
  | "uuid"
  | "relation"
  | "file"
  | "relation_many"
  | "i18n_text";

interface Field {
  name: string;
  type: FieldType;
  required?: boolean;
}

interface Collection {
  slug: string;
  singular?: string | null;
  fields: Field[];
  ownerScoped: boolean | number;
}

const TS_TYPES: Record<FieldType, string> = {
  text: "string",
  longtext: "string",
  integer: "number",
  number: "number",
  boolean: "boolean",
  json: "unknown",
  timestamp: "string",
  uuid: "string",
  // FK id (or the expanded object when read with `expand`).
  relation: "string",
  // Storage key for a `system_files` row.
  file: "string",
  // Array of foreign ids.
  relation_many: "string[]",
  // Localized map; collapses to a string when read with `?locale=xx`.
  i18n_text: "string | Record<string, string>",
};

const pascal = (s: string): string =>
  s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());

const camel = (s: string): string =>
  s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());

const renderCollection = (c: Collection): string => {
  const lines: string[] = [];
  lines.push(`export interface ${pascal(c.slug)} {`);
  lines.push(`  id: string;`);
  if (c.ownerScoped) {
    lines.push(`  ownerId: string | null;`);
  }
  lines.push(`  createdAt: string;`);
  lines.push(`  updatedAt: string;`);
  for (const f of c.fields) {
    const t = TS_TYPES[f.type] ?? "unknown";
    const opt = f.required ? "" : " | null";
    lines.push(`  ${camel(f.name)}: ${t}${opt};`);
  }
  lines.push(`}`);
  return lines.join("\n");
};

const renderRegistry = (collections: Collection[]): string => {
  const entries = collections
    .map((c) => `  ${c.slug}: ${pascal(c.slug)};`)
    .join("\n");
  return `export interface Collections {\n${entries}\n}`;
};

const SDK_IMPORT = `import {\n  createClient,\n  typedCollections,\n  type ClientOptions,\n  type TypedClient,\n} from "backlex";\n`;

const SDK_FACTORY = `/**
 * A strongly-typed backlex client. Access collections by slug — every method
 * is typed against the generated row interfaces:
 *
 *   const db = createTypedClient({ url: "https://api.your.app", apiKey });
 *   const { data } = await db.collections.posts.list(); // data: Posts[]
 *
 * The underlying client (auth, storage, \`from<T>\`, …) is still available.
 */
export const createTypedClient = (opts: ClientOptions): TypedClient<Collections> =>
  typedCollections<Collections>(createClient(opts));`;

/** Render the full TypeScript module. Pure — no I/O — so it's unit-testable. */
export const renderModule = (
  collections: Collection[],
  opts: { apiUrl: string; sdk?: boolean },
): string => {
  const banner = `// Auto-generated by \`backlex gen-types${
    opts.sdk ? " --sdk" : ""
  }\` from ${opts.apiUrl}\n// Do not edit by hand. Regenerate after schema changes.\n\n`;
  const body = [
    ...collections.map(renderCollection),
    renderRegistry(collections),
    ...(opts.sdk ? [SDK_FACTORY] : []),
  ].join("\n\n");
  return banner + (opts.sdk ? `${SDK_IMPORT}\n` : "") + body + "\n";
};

export const runGenTypes = async (
  apiUrl: string,
  outPath?: string,
  apiKey?: string,
  sdk?: boolean,
): Promise<void> => {
  const headers: Record<string, string> = {};
  if (apiKey) headers.authorization = `Bearer ${apiKey}`;
  const res = await fetch(`${apiUrl}/api/collections`, { headers });
  if (!res.ok) {
    throw new Error(`fetch ${apiUrl}/api/collections → ${res.status}`);
  }
  const body = (await res.json()) as { data: Collection[] };
  const out = renderModule(body.data, { apiUrl, sdk });

  if (outPath) {
    writeFileSync(outPath, out, "utf8");
    const what = sdk ? "typed SDK" : "types";
    console.log(`✓ wrote ${what} for ${body.data.length} collection(s) → ${outPath}`);
  } else {
    process.stdout.write(out);
  }
};
