#!/usr/bin/env bun
/**
 * Compile `apps/web/src/client/consent-banner/` into a checked-in TS module
 * holding the minified browser bundle as a string.
 *
 * ── Why a generated string and not a file under `public/` ─────────────────
 * NOT the reason the plan gave. "Bun serves no static assets" is false — the
 * Bun entry calls `mountSpa(app, serveStatic)` and `public/boot-recovery.js`
 * ships through it on every runtime. The real reason is headers: a file under
 * `public/` is served by the STATIC layer on Cloudflare, Vercel and Netlify and
 * never passes through `app.ts`'s header middleware, so it gets `_headers`'
 * strict `/*` policy with no `Cross-Origin-Resource-Policy` relaxation and no
 * `Access-Control-Allow-Origin`. And `_headers` only ever APPENDS across
 * matching rules — its own note says so — so a per-path override cannot undo
 * the strict rule. A no-cors `<script src>` from a customer's domain would be
 * discarded by the browser, which is precisely the bug that shipped three
 * times already.
 *
 * ── Why `JSON.stringify` and not a template literal ───────────────────────
 * `analytics-tracker.ts` holds its browser source in a template literal and
 * pays for it with a rule that the source contain no backtick, no `${` and no
 * backslash — enforced by a test, because a backslash there is eaten before
 * the browser sees it. A MINIFIED bundle contains all three by construction.
 * So the emitted module quotes the payload with `JSON.stringify`, following
 * `packages/db/scripts/build-manifest.ts`, and no escaping rule has to hold.
 *
 * ── Drift ─────────────────────────────────────────────────────────────────
 * `lefthook.yml` regenerates and `git diff --exit-code`s this on commit, and
 * `apps/web/tests/consent-banner.test.ts` re-runs the same comparison inside
 * `bun test`, so CI catches what a `--no-verify` push would carry through. The hook alone
 * is not enough: its glob watches the SOURCES, so editing this generator or the
 * generated file by hand never triggers it.
 */
import { writeFileSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = resolve(REPO_ROOT, "apps/web/src/client/consent-banner/index.ts");
const OUT = resolve(REPO_ROOT, "apps/web/src/server/services/consent-banner-bundle.ts");

export const buildBanner = async (): Promise<string> => {
  const built = await Bun.build({
    entrypoints: [ENTRY],
    target: "browser",
    format: "iife",
    minify: true,
  });
  if (!built.success) {
    for (const log of built.logs) console.error(log);
    throw new Error("consent banner bundle failed to build");
  }
  const out = built.outputs[0];
  if (!out) throw new Error("consent banner bundle produced no output");
  // The entry assigns `window.__backlexConsentBanner` itself, so nothing is
  // appended here — a wrapper referring to a minified internal name would
  // break the moment the minifier renamed it.
  return out.text();
};

export const emit = (code: string): string =>
  [
    "// AUTO-GENERATED by scripts/gen-consent-banner.ts — do not edit by hand.",
    "// Source: apps/web/src/client/consent-banner/",
    "// Regenerate with: bun scripts/gen-consent-banner.ts",
    "//",
    "// Quoted with JSON.stringify rather than held in a template literal: a",
    "// minified bundle contains backticks, backslashes and ${ by construction,",
    "// and the tracker's literal-safety rule cannot hold for it.",
    "",
    `export const CONSENT_BANNER_JS: string = ${JSON.stringify(code)};`,
    "",
  ].join("\n");

if (import.meta.main) {
  const code = await buildBanner();
  const body = emit(code);
  const before = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return "";
    }
  })();
  writeFileSync(OUT, body);
  console.log(
    `✓ consent banner: ${code.length} bytes → ${OUT}${before === body ? " (unchanged)" : ""}`,
  );
}
