#!/usr/bin/env bun
/**
 * Scans `packages/db/drizzle/{pg,sqlite}/` and emits a per-dialect TypeScript
 * module that text-imports every migration's `migration.sql`. The output is
 * committed to source so production bundles (Vercel, Netlify, Worker)
 * already carry every SQL statement they might need to apply at boot.
 *
 * Bun's `import "..." with { type: "text" }` inlines the file contents at
 * build time across every target we ship — no runtime fs lookups, no asset
 * bundling tricks.
 *
 * Run via `bun scripts/gen-migration-bundles.ts`. The CI pre-commit hook
 * regenerates and diff-checks the bundles so they can never drift.
 */
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");

type Dialect = "pg" | "sqlite";

const collectMigrations = (dialect: Dialect): string[] => {
  const root = join(REPO_ROOT, "packages/db/drizzle", dialect);
  if (!existsSync(root)) return [];
  return readdirSync(root)
    .filter((name) => {
      const sub = join(root, name);
      if (!statSync(sub).isDirectory()) return false;
      return existsSync(join(sub, "migration.sql"));
    })
    .sort();
};

const emit = (dialect: Dialect, names: string[]): string => {
  const lines: string[] = [];
  lines.push(
    `/* eslint-disable */`,
    `// AUTO-GENERATED by scripts/gen-migration-bundles.ts — do not edit by hand.`,
    `// Run \`bun scripts/gen-migration-bundles.ts\` after adding a migration to`,
    `// regenerate. The CI hook will fail if this file is out of sync.`,
    ``,
  );
  for (let i = 0; i < names.length; i++) {
    lines.push(
      `import m${i} from "../../drizzle/${dialect}/${names[i]}/migration.sql" with { type: "text" };`,
    );
  }
  lines.push(``);
  lines.push(`export interface Migration {`);
  lines.push(`  name: string;`);
  lines.push(`  sql: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const MIGRATIONS: readonly Migration[] = [`);
  for (let i = 0; i < names.length; i++) {
    lines.push(`  { name: ${JSON.stringify(names[i])}, sql: m${i} },`);
  }
  lines.push(`];`);
  return `${lines.join("\n")}\n`;
};

const writeBundle = (dialect: Dialect): void => {
  const names = collectMigrations(dialect);
  const out = join(REPO_ROOT, "packages/db/src", dialect, "migrations-bundle.ts");
  writeFileSync(out, emit(dialect, names));
  console.log(`✓ ${dialect}: ${names.length} migrations → ${out}`);
};

writeBundle("pg");
writeBundle("sqlite");
