/**
 * The schema behind `examples/fulfillment-ops` — a warehouse / fulfillment
 * operation: customers, stock, campaigns, order preparation (pick → pack),
 * shipments and the carriers that move them.
 *
 * Written as a plain array of `POST /api/collections` bodies rather than a
 * repo template on purpose: this is what an integrator actually sends, so
 * provisioning it is itself a test of the public create endpoint.
 *
 * Currency: the operation is domestic, so every money column is pinned to a
 * fixed `TRY` rather than reading a sibling `currency` column. That is the one
 * shape a money ROLLUP is allowed to sum (`assertRollupCurrenciesAgree` refuses
 * a `currencyField` on either side), and order totals are exactly the thing
 * that should be maintained from their lines.
 */

type Json = Record<string, unknown>;

const money = (name: string, extra: Json = {}): Json => ({
  name,
  type: "money",
  money: { currency: "TRY" },
  ...extra,
});

const dd = (
  name: string,
  choices: { value: string; label: string; color?: string }[],
  extra: Json = {},
): Json => ({
  name,
  type: "text",
  interface: "dropdown",
  options: { choices },
  ...extra,
});

export const COLLECTIONS: Json[] = [
  // ── Depo ────────────────────────────────────────────────────────────────
  {
    slug: "warehouses",
    singular: "Depo",
    plural: "Depolar",
    icon: "Warehouse",
    color: "blue",
    note: "Fiziksel depo tesisi. Stok, toplama dalgaları ve sevkiyatlar bir depoya bağlıdır.",
    displayTemplate: "{{name}}",
    defaultSort: "name",
    fields: [
      { name: "code", type: "text", required: true, unique: true, label: "Kod", width: "half" },
      { name: "name", type: "text", required: true, label: "Ad", width: "half" },
      { name: "city", type: "text", label: "Şehir", width: "half" },
      { name: "address", type: "text", label: "Adres", width: "half" },
      {
        name: "coordinates",
        type: "geo",
        label: "Harita",
        geo: { geocodeFrom: ["address", "city"] },
      },
      {
        name: "cutoff_time",
        type: "text",
        label: "Kargo son teslim saati",
        description: "Bu saatten sonra hazırlanan siparişler ertesi gün çıkar (HH:MM).",
        validation: { regex: "^([01][0-9]|2[0-3]):[0-5][0-9]$" },
        width: "half",
      },
      {
        name: "active",
        type: "boolean",
        label: "Aktif",
        default: true,
        retire: { retiredWhen: false, references: "block" },
        width: "half",
      },
    ],
  },
  {
    slug: "zones",
    singular: "Bölge",
    plural: "Bölgeler",
    icon: "LayoutGrid",
    color: "blue",
    note: "Depo içi bölge. Bir depoda aynı kod iki kez kullanılamaz.",
    displayTemplate: "{{code}} — {{name}}",
    defaultSort: "code",
    fields: [
      { name: "warehouse", type: "relation", to: "warehouses", required: true, label: "Depo", width: "half" },
      { name: "code", type: "text", required: true, uniqueWith: ["warehouse"], label: "Kod", width: "half" },
      { name: "name", type: "text", label: "Ad", width: "half" },
      ...[
        dd(
          "kind",
          [
            { value: "picking", label: "Toplama", color: "green" },
            { value: "bulk", label: "Toplu stok", color: "blue" },
            { value: "staging", label: "Hazırlık", color: "amber" },
            { value: "quarantine", label: "Karantina", color: "red" },
            { value: "shipping", label: "Sevk", color: "violet" },
          ],
          { required: true, default: "picking", label: "Tür", width: "half" },
        ),
      ],
    ],
  },
  {
    slug: "bins",
    singular: "Raf",
    plural: "Raflar",
    icon: "Boxes",
    color: "blue",
    note: "Stok tutan en küçük adres. Toplama görevleri bir rafa yönlendirilir.",
    displayTemplate: "{{code}}",
    defaultSort: "code",
    fields: [
      { name: "warehouse", type: "relation", to: "warehouses", required: true, label: "Depo", width: "half" },
      { name: "zone", type: "relation", to: "zones", required: true, label: "Bölge", width: "half" },
      { name: "code", type: "text", required: true, uniqueWith: ["warehouse"], label: "Raf kodu", width: "half" },
      { name: "capacity_units", type: "integer", label: "Kapasite (adet)", validation: { min: 0 }, width: "half" },
      {
        name: "pick_sequence",
        type: "integer",
        label: "Toplama sırası",
        description: "Toplayıcının bu rafa uğrama sırası. Aynı depodaki raflar tek bir liste olarak sıralanır.",
        order: { scope: "warehouse" },
      },
      { name: "active", type: "boolean", label: "Aktif", default: true, retire: { retiredWhen: false, references: "block" } },
    ],
  },

  // ── Katalog & stok ──────────────────────────────────────────────────────
  {
    slug: "products",
    singular: "Ürün",
    plural: "Ürünler",
    icon: "Package",
    color: "violet",
    fts: true,
    displayTemplate: "{{sku}} — {{name}}",
    defaultSort: "name",
    fields: [
      { name: "sku", type: "text", required: true, unique: true, label: "SKU", width: "half" },
      { name: "barcode", type: "text", unique: true, indexed: true, label: "Barkod", width: "half" },
      { name: "name", type: "text", required: true, searchable: true, label: "Ad" },
      { name: "description", type: "longtext", searchable: true, label: "Açıklama" },
      ...[
        dd(
          "category",
          [
            { value: "gida", label: "Gıda", color: "green" },
            { value: "kozmetik", label: "Kozmetik", color: "pink" },
            { value: "elektronik", label: "Elektronik", color: "blue" },
            { value: "tekstil", label: "Tekstil", color: "amber" },
            { value: "ev", label: "Ev & Yaşam", color: "teal" },
          ],
          { label: "Kategori", indexed: true, width: "half" },
        ),
      ],
      money("list_price", { label: "Liste fiyatı", required: true, width: "half" }),
      { name: "weight_g", type: "integer", label: "Ağırlık (g)", validation: { min: 0 }, width: "half" },
      { name: "volume_cm3", type: "integer", label: "Hacim (cm³)", validation: { min: 0 }, width: "half" },
      {
        name: "shelf_life_days",
        type: "integer",
        label: "Raf ömrü (gün)",
        description: "Boş bırakılırsa ürün son kullanma tarihi takip etmez.",
        validation: { min: 1 },
        width: "half",
      },
      {
        name: "on_hand_total",
        type: "integer",
        label: "Toplam eldeki stok",
        description: "Tüm raflardaki fiziksel stok toplamı — sunucu tarafından stok seviyelerinden hesaplanır.",
        rollup: { from: "stock_levels", via: "product", fn: "sum", field: "on_hand" },
        width: "half",
      },
      { name: "active", type: "boolean", label: "Satışta", default: true, retire: { retiredWhen: false, references: "block" } },
    ],
  },
  {
    slug: "stock_levels",
    singular: "Stok seviyesi",
    plural: "Stok seviyeleri",
    icon: "Layers",
    color: "teal",
    note: "Bir ürünün bir raftaki miktarı. Ürün × raf çifti tektir — aynı çift için ikinci satır reddedilir.",
    displayTemplate: "{{product}} @ {{bin}}",
    defaultSort: "-on_hand",
    fields: [
      { name: "product", type: "relation", to: "products", required: true, label: "Ürün", width: "half" },
      { name: "bin", type: "relation", to: "bins", required: true, uniqueWith: ["product"], label: "Raf", width: "half" },
      { name: "on_hand", type: "integer", required: true, default: 0, label: "Eldeki", validation: { min: 0 }, width: "half" },
      {
        name: "committed",
        type: "integer",
        label: "Rezerve",
        description: "Bu seviyeye karşı açık duran rezervasyonların toplamı — elle yazılamaz.",
        rollup: {
          from: "stock_reservations",
          via: "level",
          fn: "sum",
          field: "qty",
          filter: { status: { _eq: "held" } },
        },
        width: "half",
      },
      { name: "min_qty", type: "integer", label: "Minimum", validation: { min: 0 }, width: "half" },
      { name: "reorder_point", type: "integer", label: "Sipariş noktası", validation: { min: 0 }, width: "half" },
      { name: "counted_at", type: "timestamp", label: "Son sayım" },
    ],
  },
  {
    slug: "stock_reservations",
    singular: "Rezervasyon",
    plural: "Rezervasyonlar",
    icon: "Lock",
    color: "amber",
    note: "Bir sipariş satırı için ayrılan stok. `level` alanı zorunludur: rezervasyonu somut bir stok seviyesine bağlamayan bir model, rezerve miktarı asla hesaplayamaz.",
    defaultSort: "-created_at",
    fields: [
      { name: "level", type: "relation", to: "stock_levels", required: true, label: "Stok seviyesi", width: "half" },
      { name: "order_line", type: "relation", to: "order_lines", required: true, label: "Sipariş satırı", width: "half" },
      { name: "qty", type: "integer", required: true, label: "Miktar", validation: { min: 1 }, width: "half" },
      ...[
        dd(
          "status",
          [
            { value: "held", label: "Tutuluyor", color: "amber" },
            { value: "consumed", label: "Kullanıldı", color: "green" },
            { value: "released", label: "Serbest", color: "gray" },
          ],
          {
            required: true,
            default: "held",
            label: "Durum",
            width: "half",
            transitions: {
              initial: ["held"],
              allow: [
                { from: "held", to: "consumed", label: "Topla" },
                { from: "held", to: "released", label: "Serbest bırak" },
              ],
            },
          },
        ),
      ],
          ],
  },
  {
    slug: "stock_movements",
    singular: "Stok hareketi",
    plural: "Stok hareketleri",
    icon: "ArrowLeftRight",
    color: "teal",
    note: "Değişmez hareket defteri. Bir transfer TEK satır değil, aynı `reference` değerini paylaşan biri eksi biri artı İKİ satırdır — her stok raporu `SUM(qty) WHERE bin = X` sorar.",
    defaultSort: "-occurred_at",
    fields: [
      { name: "product", type: "relation", to: "products", required: true, label: "Ürün", width: "half" },
      { name: "bin", type: "relation", to: "bins", required: true, label: "Raf", width: "half" },
      {
        name: "qty",
        type: "integer",
        required: true,
        label: "Miktar",
        description: "İşaretli: girişte artı, çıkışta eksi.",
        width: "half",
      },
      ...[
        dd(
          "reason",
          [
            { value: "receipt", label: "Mal kabul", color: "green" },
            { value: "pick", label: "Toplama", color: "blue" },
            { value: "adjustment", label: "Sayım farkı", color: "amber" },
            { value: "transfer", label: "Transfer", color: "violet" },
            { value: "return", label: "İade girişi", color: "teal" },
            { value: "damage", label: "Hasar/fire", color: "red" },
          ],
          { required: true, label: "Neden", indexed: true, width: "half" },
        ),
      ],
      {
        name: "reference",
        type: "text",
        indexed: true,
        label: "Referans",
        description: "Transferin iki ayağını birbirine bağlayan değer; ya da sipariş/mal kabul numarası.",
      },
      { name: "occurred_at", type: "timestamp", onCreate: "now", label: "Zaman", width: "half" },
      { name: "actor", type: "text", onCreate: "user", label: "Kaydeden", width: "half" },
    ],
  },

  // ── Müşteriler ──────────────────────────────────────────────────────────
  {
    slug: "customers",
    singular: "Müşteri",
    plural: "Müşteriler",
    icon: "Users",
    color: "green",
    fts: true,
    displayTemplate: "{{name}}",
    defaultSort: "name",
    fields: [
      {
        name: "code",
        type: "text",
        label: "Müşteri no",
        sequence: { pattern: "MUS-{#####}", reset: "never", timezone: "Europe/Istanbul" },
        width: "half",
      },
      { name: "name", type: "text", required: true, searchable: true, label: "Ünvan", width: "half" },
      ...[
        dd(
          "kind",
          [
            { value: "bireysel", label: "Bireysel", color: "blue" },
            { value: "kurumsal", label: "Kurumsal", color: "violet" },
          ],
          { required: true, default: "bireysel", label: "Tip", width: "half" },
        ),
      ],
      ...[
        dd(
          "segment",
          [
            { value: "standart", label: "Standart", color: "gray" },
            { value: "gumus", label: "Gümüş", color: "slate" },
            { value: "altin", label: "Altın", color: "amber" },
            { value: "platin", label: "Platin", color: "violet" },
          ],
          { default: "standart", label: "Segment", indexed: true, width: "half" },
        ),
      ],
      { name: "email", type: "email", label: "E-posta", width: "half" },
      { name: "phone", type: "phone", phone: { region: "TR" }, label: "Telefon", width: "half" },
      {
        name: "tax_office",
        type: "text",
        label: "Vergi dairesi",
        width: "half",
        conditions: [{ name: "kurumsal", rule: { kind: { _eq: "kurumsal" } }, required: true }],
      },
      {
        name: "tax_no",
        type: "text",
        label: "Vergi/TC no",
        width: "half",
        conditions: [{ name: "kurumsal", rule: { kind: { _eq: "kurumsal" } }, required: true }],
      },
      money("credit_limit", { label: "Kredi limiti", width: "half" }),
      {
        name: "orders_count",
        type: "integer",
        label: "Sipariş adedi",
        description: "İptal edilmemiş siparişlerden sayılır.",
        rollup: {
          from: "orders",
          via: "customer",
          fn: "count",
          filter: { status: { _neq: "cancelled" } },
        },
        width: "half",
      },
      { name: "active", type: "boolean", label: "Aktif", default: true, retire: { retiredWhen: false, references: "block" } },
    ],
  },
  {
    slug: "customer_addresses",
    singular: "Adres",
    plural: "Adresler",
    icon: "MapPin",
    color: "green",
    displayTemplate: "{{label}} — {{city}}",
    defaultSort: "label",
    fields: [
      { name: "customer", type: "relation", to: "customers", required: true, onDelete: "cascade", label: "Müşteri", width: "half" },
      { name: "label", type: "text", required: true, label: "Etiket", width: "half" },
      { name: "contact_name", type: "text", label: "Teslim alacak kişi", width: "half" },
      { name: "phone", type: "phone", phone: { region: "TR" }, label: "Telefon", width: "half" },
      { name: "line1", type: "text", required: true, label: "Adres" },
      { name: "district", type: "text", label: "İlçe", width: "half" },
      { name: "city", type: "text", required: true, label: "Şehir", width: "half" },
      { name: "postcode", type: "text", label: "Posta kodu", width: "half" },
      { name: "country", type: "text", default: "TR", label: "Ülke", width: "half" },
      { name: "coordinates", type: "geo", label: "Harita", geo: { geocodeFrom: ["line1", "district", "city"] } },
      { name: "is_default", type: "boolean", label: "Varsayılan", default: false },
    ],
  },

  // ── Kampanyalar ─────────────────────────────────────────────────────────
  {
    slug: "campaigns",
    singular: "Kampanya",
    plural: "Kampanyalar",
    icon: "Megaphone",
    color: "pink",
    displayTemplate: "{{name}}",
    defaultSort: "-starts_at",
    kanbanGroupBy: "status",
    fields: [
      { name: "name", type: "text", required: true, label: "Ad", width: "half" },
      { name: "code", type: "text", unique: true, label: "Kupon kodu", width: "half" },
      ...[
        dd(
          "kind",
          [
            { value: "percent", label: "Yüzde indirim", color: "blue" },
            { value: "amount", label: "Tutar indirim", color: "green" },
            { value: "free_shipping", label: "Ücretsiz kargo", color: "teal" },
          ],
          { required: true, default: "percent", label: "Tür", width: "half" },
        ),
      ],
      {
        name: "percent_off",
        type: "number",
        label: "İndirim oranı",
        format: { style: "percent100", precision: 0 },
        validation: { min: 0, max: 100 },
        visibleWhen: { field: "kind", op: "_eq", value: "percent" },
        conditions: [{ name: "yuzde", rule: { kind: { _eq: "percent" } }, required: true }],
        width: "half",
      },
      money("amount_off", {
        label: "İndirim tutarı",
        visibleWhen: { field: "kind", op: "_eq", value: "amount" },
        conditions: [{ name: "tutar", rule: { kind: { _eq: "amount" } }, required: true }],
        width: "half",
      }),
      money("min_basket", { label: "Minimum sepet", width: "half" }),
      {
        name: "starts_at",
        type: "timestamp",
        required: true,
        label: "Başlangıç",
        range: { end: "ends_at", bounds: "[)", ordered: true },
        width: "half",
      },
      { name: "ends_at", type: "timestamp", required: true, label: "Bitiş", width: "half" },
      money("budget", { label: "Bütçe", width: "half" }),
      {
        name: "spent",
        type: "money",
        money: { currency: "TRY" },
        label: "Harcanan",
        description: "Bu kampanyayla verilen indirimlerin toplamı.",
        rollup: { from: "campaign_redemptions", via: "campaign", fn: "sum", field: "discount_amount" },
        width: "half",
      },
      {
        name: "usage_limit",
        type: "integer",
        label: "Kullanım limiti",
        validation: { min: 1 },
        width: "half",
      },
      {
        name: "redemption_count",
        type: "integer",
        label: "Kullanım",
        rollup: { from: "campaign_redemptions", via: "campaign", fn: "count" },
        width: "half",
      },
      ...[
        dd(
          "channel",
          [
            { value: "web", label: "Web", color: "blue" },
            { value: "marketplace", label: "Pazaryeri", color: "amber" },
            { value: "magaza", label: "Mağaza", color: "green" },
            { value: "hepsi", label: "Tümü", color: "violet" },
          ],
          { default: "hepsi", label: "Kanal", width: "half" },
        ),
      ],
      ...[
        dd(
          "status",
          [
            { value: "draft", label: "Taslak", color: "gray" },
            { value: "scheduled", label: "Planlandı", color: "blue" },
            { value: "active", label: "Yayında", color: "green" },
            { value: "paused", label: "Duraklatıldı", color: "amber" },
            { value: "ended", label: "Bitti", color: "slate" },
          ],
          {
            required: true,
            default: "draft",
            label: "Durum",
            indexed: true,
            width: "half",
            transitions: {
              initial: ["draft"],
              allow: [
                { from: "draft", to: "scheduled", label: "Planla", requires: ["starts_at", "ends_at"] },
                { from: "scheduled", to: "active", label: "Yayına al" },
                { from: "active", to: "paused", label: "Duraklat" },
                { from: "paused", to: "active", label: "Devam et" },
                { from: "active", to: "ended", label: "Bitir" },
                { from: "paused", to: "ended", label: "Bitir" },
                { from: "scheduled", to: "draft", label: "Taslağa al" },
              ],
            },
          },
        ),
      ],
    ],
  },
  {
    slug: "campaign_products",
    singular: "Kampanya ürünü",
    plural: "Kampanya ürünleri",
    icon: "Tag",
    color: "pink",
    hidden: true,
    note: "Kampanyanın kapsadığı ürünler. Boşsa kampanya tüm katalogda geçerlidir.",
    fields: [
      { name: "campaign", type: "relation", to: "campaigns", required: true, onDelete: "cascade", label: "Kampanya", width: "half" },
      { name: "product", type: "relation", to: "products", required: true, uniqueWith: ["campaign"], label: "Ürün", width: "half" },
    ],
  },
  {
    slug: "campaign_redemptions",
    singular: "Kampanya kullanımı",
    plural: "Kampanya kullanımları",
    icon: "TicketCheck",
    color: "pink",
    defaultSort: "-redeemed_at",
    fields: [
      { name: "campaign", type: "relation", to: "campaigns", required: true, label: "Kampanya", width: "half" },
      { name: "order", type: "relation", to: "orders", required: true, uniqueWith: ["campaign"], label: "Sipariş", width: "half" },
      { name: "customer", type: "relation", to: "customers", label: "Müşteri", width: "half" },
      money("discount_amount", { label: "İndirim", required: true, width: "half" }),
      { name: "redeemed_at", type: "timestamp", onCreate: "now", label: "Zaman" },
    ],
  },

  // ── Siparişler ve hazırlık ──────────────────────────────────────────────
  {
    slug: "orders",
    singular: "Sipariş",
    plural: "Siparişler",
    icon: "ShoppingCart",
    color: "amber",
    fts: true,
    displayTemplate: "{{order_no}}",
    defaultSort: "-placed_at",
    kanbanGroupBy: "status",
    fields: [
      {
        name: "order_no",
        type: "text",
        label: "Sipariş no",
        searchable: true,
        sequence: { pattern: "SIP-{YYYY}-{#####}", reset: "yearly", timezone: "Europe/Istanbul" },
        width: "half",
      },
      { name: "customer", type: "relation", to: "customers", required: true, label: "Müşteri", width: "half" },
      { name: "shipping_address", type: "relation", to: "customer_addresses", required: true, label: "Teslimat adresi", width: "half" },
      { name: "warehouse", type: "relation", to: "warehouses", required: true, label: "Çıkış deposu", width: "half" },
      ...[
        dd(
          "channel",
          [
            { value: "web", label: "Web", color: "blue" },
            { value: "marketplace", label: "Pazaryeri", color: "amber" },
            { value: "telefon", label: "Telefon", color: "teal" },
            { value: "magaza", label: "Mağaza", color: "green" },
          ],
          { required: true, default: "web", label: "Kanal", indexed: true, width: "half" },
        ),
      ],
      ...[
        dd(
          "priority",
          [
            { value: "standart", label: "Standart", color: "gray" },
            { value: "hizli", label: "Hızlı", color: "amber" },
            { value: "ayni_gun", label: "Aynı gün", color: "red" },
          ],
          { required: true, default: "standart", label: "Öncelik", width: "half" },
        ),
      ],
      ...[
        dd(
          "status",
          [
            { value: "new", label: "Yeni", color: "slate" },
            { value: "confirmed", label: "Onaylandı", color: "blue" },
            { value: "picking", label: "Toplanıyor", color: "amber" },
            { value: "packed", label: "Paketlendi", color: "violet" },
            { value: "shipped", label: "Sevk edildi", color: "teal" },
            { value: "delivered", label: "Teslim edildi", color: "green" },
            { value: "cancelled", label: "İptal", color: "red" },
          ],
          {
            required: true,
            default: "new",
            label: "Durum",
            indexed: true,
            transitions: {
              initial: ["new"],
              allow: [
                { from: "new", to: "confirmed", label: "Onayla" },
                { from: "new", to: "cancelled", label: "İptal et" },
                { from: "confirmed", to: "picking", label: "Toplamaya al" },
                { from: "confirmed", to: "cancelled", label: "İptal et" },
                { from: "picking", to: "packed", label: "Paketlendi" },
                { from: "picking", to: "cancelled", label: "İptal et" },
                { from: "packed", to: "shipped", label: "Sevk et" },
                { from: "shipped", to: "delivered", label: "Teslim edildi" },
              ],
            },
          },
        ),
      ],
      { name: "placed_at", type: "timestamp", required: true, onCreate: "now", label: "Sipariş tarihi", width: "half" },
      { name: "promised_at", type: "timestamp", label: "Söz verilen teslim", width: "half" },
      {
        name: "line_count",
        type: "integer",
        label: "Satır adedi",
        rollup: { from: "order_lines", via: "order", fn: "count" },
        width: "half",
      },
      {
        name: "items_total",
        type: "money",
        money: { currency: "TRY" },
        label: "Ürün toplamı",
        description: "Sipariş satırlarının toplamı — sunucu tarafından hesaplanır.",
        rollup: { from: "order_lines", via: "order", fn: "sum", field: "line_total" },
        width: "half",
      },
      money("discount_total", { label: "İndirim", width: "half" }),
      money("shipping_fee", { label: "Kargo ücreti", width: "half" }),
      money("grand_total", { label: "Genel toplam", width: "half" }),
      { name: "notes", type: "longtext", label: "Not" },
    ],
  },
  {
    slug: "order_lines",
    singular: "Sipariş satırı",
    plural: "Sipariş satırları",
    icon: "List",
    color: "amber",
    hidden: true,
    fields: [
      { name: "order", type: "relation", to: "orders", required: true, onDelete: "cascade", label: "Sipariş", width: "half" },
      { name: "product", type: "relation", to: "products", required: true, uniqueWith: ["order"], label: "Ürün", width: "half" },
      { name: "qty", type: "integer", required: true, default: 1, label: "Miktar", validation: { min: 1 }, width: "half" },
      { name: "qty_picked", type: "integer", default: 0, label: "Toplanan", validation: { min: 0 }, width: "half" },
      money("unit_price", { label: "Birim fiyat", required: true, width: "half" }),
      money("line_total", { label: "Satır toplamı", required: true, width: "half" }),
    ],
  },
  {
    slug: "pick_waves",
    singular: "Toplama dalgası",
    plural: "Toplama dalgaları",
    icon: "Waves",
    color: "orange",
    note: "Tek seferde toplanacak görevler kümesi. Bir dalga tek depoya aittir.",
    displayTemplate: "{{wave_no}}",
    defaultSort: "-planned_at",
    kanbanGroupBy: "status",
    fields: [
      {
        name: "wave_no",
        type: "text",
        label: "Dalga no",
        sequence: { pattern: "DLG-{YYYY}{MM}-{####}", reset: "monthly", timezone: "Europe/Istanbul" },
        width: "half",
      },
      { name: "warehouse", type: "relation", to: "warehouses", required: true, label: "Depo", width: "half" },
      ...[
        dd(
          "status",
          [
            { value: "planned", label: "Planlandı", color: "slate" },
            { value: "released", label: "Sahaya verildi", color: "blue" },
            { value: "in_progress", label: "Toplanıyor", color: "amber" },
            { value: "completed", label: "Tamamlandı", color: "green" },
            { value: "cancelled", label: "İptal", color: "red" },
          ],
          {
            required: true,
            default: "planned",
            label: "Durum",
            indexed: true,
            width: "half",
            transitions: {
              initial: ["planned"],
              allow: [
                { from: "planned", to: "released", label: "Sahaya ver" },
                { from: "planned", to: "cancelled", label: "İptal" },
                { from: "released", to: "in_progress", label: "Başladı" },
                { from: "released", to: "cancelled", label: "İptal" },
                { from: "in_progress", to: "completed", label: "Tamamla" },
              ],
            },
          },
        ),
      ],
      { name: "assigned_to", type: "text", label: "Toplayıcı", width: "half" },
      { name: "planned_at", type: "timestamp", onCreate: "now", label: "Planlanma", width: "half" },
      { name: "released_at", type: "timestamp", label: "Sahaya verilme", width: "half" },
      {
        name: "task_count",
        type: "integer",
        label: "Görev adedi",
        rollup: { from: "pick_tasks", via: "wave", fn: "count" },
        width: "half",
      },
      {
        name: "units_picked",
        type: "integer",
        label: "Toplanan adet",
        rollup: { from: "pick_tasks", via: "wave", fn: "sum", field: "qty_picked" },
        width: "half",
      },
    ],
  },
  {
    slug: "pick_tasks",
    singular: "Toplama görevi",
    plural: "Toplama görevleri",
    icon: "ClipboardList",
    color: "orange",
    note: "Bir rafa git, şu üründen şu kadar al. Sıra alanı raf gezinme sırasını taşır ve dalga içinde bölümlenir.",
    defaultSort: "sequence",
    kanbanGroupBy: "status",
    fields: [
      { name: "wave", type: "relation", to: "pick_waves", required: true, onDelete: "cascade", label: "Dalga", width: "half" },
      { name: "order", type: "relation", to: "orders", required: true, label: "Sipariş", width: "half" },
      { name: "order_line", type: "relation", to: "order_lines", required: true, label: "Sipariş satırı", width: "half" },
      { name: "product", type: "relation", to: "products", required: true, label: "Ürün", width: "half" },
      { name: "bin", type: "relation", to: "bins", required: true, label: "Raf", width: "half" },
      { name: "qty_required", type: "integer", required: true, label: "İstenen", validation: { min: 1 }, width: "half" },
      { name: "qty_picked", type: "integer", default: 0, label: "Toplanan", validation: { min: 0 }, width: "half" },
      {
        name: "sequence",
        type: "integer",
        label: "Sıra",
        order: { scope: "wave" },
        width: "half",
      },
      { name: "picker", type: "text", label: "Toplayan", width: "half" },
      ...[
        dd(
          "status",
          [
            { value: "pending", label: "Bekliyor", color: "slate" },
            { value: "picking", label: "Toplanıyor", color: "amber" },
            { value: "picked", label: "Toplandı", color: "green" },
            { value: "short", label: "Eksik", color: "red" },
          ],
          {
            required: true,
            default: "pending",
            label: "Durum",
            indexed: true,
            width: "half",
            transitions: {
              initial: ["pending"],
              allow: [
                { from: "pending", to: "picking", label: "Başla" },
                { from: "picking", to: "picked", label: "Toplandı", requires: ["qty_picked"] },
                { from: "picking", to: "short", label: "Eksik bildir" },
                { from: "short", to: "picking", label: "Tekrar dene" },
              ],
            },
          },
        ),
      ],
      { name: "picked_at", type: "timestamp", label: "Toplanma zamanı" },
    ],
  },
  {
    slug: "packages",
    singular: "Koli",
    plural: "Koliler",
    icon: "PackageCheck",
    color: "violet",
    displayTemplate: "{{package_no}}",
    defaultSort: "-packed_at",
    fields: [
      {
        name: "package_no",
        type: "text",
        label: "Koli no",
        sequence: { pattern: "KOL-{YYYY}-{######}", reset: "yearly", timezone: "Europe/Istanbul" },
        width: "half",
      },
      { name: "order", type: "relation", to: "orders", required: true, label: "Sipariş", width: "half" },
      { name: "weight_g", type: "integer", label: "Ağırlık (g)", validation: { min: 0 }, width: "half" },
      { name: "length_cm", type: "integer", label: "Boy (cm)", validation: { min: 0 }, width: "half" },
      { name: "width_cm", type: "integer", label: "En (cm)", validation: { min: 0 }, width: "half" },
      { name: "height_cm", type: "integer", label: "Yükseklik (cm)", validation: { min: 0 }, width: "half" },
      {
        name: "unit_count",
        type: "integer",
        label: "İçindeki adet",
        rollup: { from: "package_lines", via: "package", fn: "sum", field: "qty" },
        width: "half",
      },
      { name: "packed_by", type: "text", label: "Paketleyen", width: "half" },
      { name: "packed_at", type: "timestamp", label: "Paketleme zamanı", width: "half" },
      ...[
        dd(
          "status",
          [
            { value: "open", label: "Açık", color: "amber" },
            { value: "sealed", label: "Kapatıldı", color: "blue" },
            { value: "handed_over", label: "Kargoya verildi", color: "green" },
          ],
          {
            required: true,
            default: "open",
            label: "Durum",
            width: "half",
            transitions: {
              initial: ["open"],
              allow: [
                { from: "open", to: "sealed", label: "Kapat", requires: ["weight_g"] },
                { from: "sealed", to: "handed_over", label: "Kargoya ver" },
                { from: "sealed", to: "open", label: "Yeniden aç" },
              ],
            },
          },
        ),
      ],
    ],
  },
  {
    slug: "package_lines",
    singular: "Koli içeriği",
    plural: "Koli içerikleri",
    icon: "ListChecks",
    color: "violet",
    hidden: true,
    fields: [
      { name: "package", type: "relation", to: "packages", required: true, onDelete: "cascade", label: "Koli", width: "half" },
      { name: "product", type: "relation", to: "products", required: true, uniqueWith: ["package"], label: "Ürün", width: "half" },
      { name: "qty", type: "integer", required: true, label: "Miktar", validation: { min: 1 }, width: "half" },
    ],
  },

  // ── Kargo ve sevkiyat ───────────────────────────────────────────────────
  {
    slug: "carriers",
    singular: "Kargo firması",
    plural: "Kargo firmaları",
    icon: "Truck",
    color: "cyan",
    displayTemplate: "{{name}}",
    defaultSort: "name",
    fields: [
      { name: "code", type: "text", required: true, unique: true, label: "Kod", width: "half" },
      { name: "name", type: "text", required: true, label: "Ad", width: "half" },
      {
        name: "tracking_url_template",
        type: "text",
        label: "Takip URL şablonu",
        description: "{{tracking_no}} yer tutucusunu içerir.",
      },
      { name: "support_phone", type: "phone", phone: { region: "TR" }, label: "Destek hattı", width: "half" },
      { name: "cutoff_time", type: "text", label: "Son teslim saati", validation: { regex: "^([01][0-9]|2[0-3]):[0-5][0-9]$" }, width: "half" },
      { name: "active", type: "boolean", label: "Aktif", default: true, retire: { retiredWhen: false, references: "block" } },
    ],
  },
  {
    slug: "shipments",
    singular: "Sevkiyat",
    plural: "Sevkiyatlar",
    icon: "Send",
    color: "cyan",
    fts: true,
    displayTemplate: "{{shipment_no}}",
    defaultSort: "-created_at",
    kanbanGroupBy: "status",
    fields: [
      {
        name: "shipment_no",
        type: "text",
        label: "Sevkiyat no",
        searchable: true,
        sequence: { pattern: "SVK-{YYYY}-{#####}", reset: "yearly", timezone: "Europe/Istanbul" },
        width: "half",
      },
      { name: "order", type: "relation", to: "orders", required: true, label: "Sipariş", width: "half" },
      { name: "package", type: "relation", to: "packages", label: "Koli", width: "half" },
      { name: "carrier", type: "relation", to: "carriers", required: true, label: "Kargo firması", width: "half" },
      {
        name: "tracking_no",
        type: "text",
        indexed: true,
        searchable: true,
        label: "Takip no",
        width: "half",
      },
      ...[
        dd(
          "service",
          [
            { value: "standart", label: "Standart", color: "gray" },
            { value: "ekspres", label: "Ekspres", color: "amber" },
            { value: "ayni_gun", label: "Aynı gün", color: "red" },
          ],
          { required: true, default: "standart", label: "Servis", width: "half" },
        ),
      ],
      ...[
        dd(
          "status",
          [
            { value: "created", label: "Oluşturuldu", color: "slate" },
            { value: "handed_over", label: "Kargoya verildi", color: "blue" },
            { value: "in_transit", label: "Yolda", color: "amber" },
            { value: "out_for_delivery", label: "Dağıtımda", color: "violet" },
            { value: "delivered", label: "Teslim edildi", color: "green" },
            { value: "returned", label: "İade", color: "orange" },
            { value: "lost", label: "Kayıp", color: "red" },
          ],
          {
            required: true,
            default: "created",
            label: "Durum",
            indexed: true,
            transitions: {
              initial: ["created"],
              allow: [
                { from: "created", to: "handed_over", label: "Kargoya ver", requires: ["tracking_no"] },
                { from: "handed_over", to: "in_transit", label: "Yola çıktı" },
                { from: "in_transit", to: "out_for_delivery", label: "Dağıtıma çıktı" },
                { from: "out_for_delivery", to: "delivered", label: "Teslim edildi" },
                { from: "out_for_delivery", to: "in_transit", label: "Depoya döndü" },
                { from: "in_transit", to: "returned", label: "İade" },
                { from: "out_for_delivery", to: "returned", label: "İade" },
                { from: "in_transit", to: "lost", label: "Kayıp" },
              ],
            },
          },
        ),
      ],
      { name: "recipient_name", type: "text", label: "Alıcı", width: "half" },
      { name: "recipient_phone", type: "phone", phone: { region: "TR" }, label: "Alıcı telefonu", width: "half" },
      { name: "destination_city", type: "text", indexed: true, label: "Varış şehri", width: "half" },
      { name: "weight_g", type: "integer", label: "Ağırlık (g)", validation: { min: 0 }, width: "half" },
      money("cost", { label: "Kargo maliyeti", width: "half" }),
      {
        name: "event_count",
        type: "integer",
        label: "Hareket adedi",
        rollup: { from: "shipment_events", via: "shipment", fn: "count" },
        width: "half",
      },
            { name: "dispatched_at", type: "timestamp", label: "Çıkış", width: "half" },
      { name: "delivered_at", type: "timestamp", label: "Teslim", width: "half" },
    ],
  },
  {
    slug: "shipment_events",
    singular: "Kargo hareketi",
    plural: "Kargo hareketleri",
    icon: "Activity",
    color: "cyan",
    defaultSort: "-occurred_at",
    fields: [
      { name: "shipment", type: "relation", to: "shipments", required: true, onDelete: "cascade", label: "Sevkiyat", width: "half" },
      ...[
        dd(
          "status",
          [
            { value: "handed_over", label: "Kargoya verildi", color: "blue" },
            { value: "in_transit", label: "Transfer merkezinde", color: "amber" },
            { value: "out_for_delivery", label: "Dağıtımda", color: "violet" },
            { value: "delivery_failed", label: "Teslim edilemedi", color: "orange" },
            { value: "delivered", label: "Teslim edildi", color: "green" },
            { value: "returned", label: "İade", color: "red" },
          ],
          { required: true, label: "Durum", width: "half" },
        ),
      ],
      { name: "location", type: "text", label: "Konum", width: "half" },
      { name: "occurred_at", type: "timestamp", required: true, onCreate: "now", label: "Zaman", width: "half" },
      { name: "description", type: "text", label: "Açıklama" },
    ],
  },
];
