/**
 * Walks `drizzle/{sqlite,pg}/*\/migration.sql`, hashes each file with SHA-256
 * (matching drizzle-orm's own hashing — see node_modules/drizzle-orm/migrator.js),
 * and writes a generated TS module mapping `hash → folder tag`.
 *
 * Drizzle's __drizzle_migrations table only records `id, hash, created_at` —
 * the human-readable folder name (e.g. `20260510150000_folders_tenant_id`)
 * never lands in the DB. The admin Migrations page joins on this manifest
 * to display tags instead of raw hashes.
 *
 *   bun run packages/db/scripts/build-manifest.ts
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(import.meta.url), "../..");
const out = resolve(root, "src/migrations-manifest.generated.ts");

const collect = (dialect: "sqlite" | "pg"): Array<[string, string]> => {
  const dir = resolve(root, "drizzle", dialect);
  const tags = readdirSync(dir)
    .filter((n) => n !== "meta")
    .filter((n) => statSync(resolve(dir, n)).isDirectory())
    .sort();
  return tags
    .map((tag): [string, string] | null => {
      const sqlPath = resolve(dir, tag, "migration.sql");
      try {
        const sql = readFileSync(sqlPath, "utf8");
        const hash = createHash("sha256").update(sql).digest("hex");
        return [hash, tag];
      } catch {
        return null;
      }
    })
    .filter((x): x is [string, string] => x !== null);
};

const sqlite = collect("sqlite");
const pg = collect("pg");

const fmt = (entries: Array<[string, string]>) =>
  entries.map(([h, t]) => `  ${JSON.stringify(h)}: ${JSON.stringify(t)},`).join("\n");

const body = `// AUTO-GENERATED by packages/db/scripts/build-manifest.ts — do not edit.
// Maps drizzle migration sha256 hash → folder tag for both dialects.
// Regenerate with: bun run --cwd packages/db manifest

export const MIGRATION_TAGS_SQLITE: Record<string, string> = {
${fmt(sqlite)}
};

export const MIGRATION_TAGS_PG: Record<string, string> = {
${fmt(pg)}
};
`;

writeFileSync(out, body);
console.log(`✓ Wrote ${out}`);
console.log(`  · sqlite: ${sqlite.length} migration(s)`);
console.log(`  · pg:     ${pg.length} migration(s)`);
